### ISSUE TITLE
Support options such as _ttl (time to live)

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#10]
https://github.com/jamescarr/mongoosastic/issues/122#issue-44362874

> Would it be possible to add support for defining additional mapping options (specifically _ttl)? See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-ttl-field.html for reference

**Comment by isayme** [comment]
closed since the feature is deprecated in 2.0.0-beta2. 

refer: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-ttl-field.html
