### ISSUE TITLE
Error searching string inside a number

### ISSUE THREAD

**Issue by santomegonzalo** [mongoosastic/mongoosastic#108]
Hello, so everything works perfect and I really love mongoosastic with elastic search.
But I have a big problem here and I have no idea how to solve it... 

in my schema i have 
"sid",
"name",
"description"

And if i search for a number everything its perfect... but if i tried to search "hello" the server crash...

this is how im searching

```
MyModel.search(
        {
            "filtered": {
                "query": {
                    "multi_match": {
                        "query": "hello",
                        "fields": ["sid", "name", "description"],
                        "analyzer": "standard",
                        "operator": "and"
                    }
                },
                "filter": {
                    "and": [
                        {
                            "term": {
                                "something": some_id
                            }
                        },
                        {
                            "term": {
                                "something_else": true
                            }
                        }
                    ]
                }
            }

        }, function( err, results ) {
});
```

BTW I tried to set es_type: "string" on my sid attribute and that didn't helped me

Thanks
Gonzalo

**Comment by guumaster** [comment]
The `search` method is just a proxy to the esClient, an instance of `elasticsearch` library. I'm guessing that the ES server is the one that crashes. Try to do an individual search,  directly with an ES query instead of `MyModel.search`, or post more info about your schema  and the crash message. If standalone search fails, maybe the plugin is not the problem.

**Comment by gsantome** [comment]
Thanks for your reply @guumaster ... Exactly the exception that im getting is NumberFormatException[For input string: "F"] (this is when im trying to search just "F")
Its a long message... but basically is "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed" and the NumberFormatException.
Do you have an idea how i could solve this?

Because I want to search "1 hello"... so I can't just check if the term is a number or not and cast...

Thanks!

**Comment by gsantome** [comment]
I'm searching for that error on elastic search... and they are saying to disabled "automatic mapping" and set an explicit mapping... and i have no idea how to make that with mongoosastic...

Thanks!

**Comment by guumaster** [comment]
Please post your complete schema definition, maybe we can see/try what's wrong.

**Comment by gsantome** [comment]
Sorry... this is my schema

```
var MySchema = new Schema({
	sid: {type: Number, es_indexed: true, es_type: "string"},
	name: {type: String, es_indexed: true, es_analyzer: "autocomplete"},
	description: {type: String, es_indexed: true, es_analyzer: "autocomplete"},
	created_by: { type: ObjectId, ref: 'users' },
	created: { type: Date, default: Date.now}
});

var MyModel = mongoose.model('entities', MySchema);

```

and i have a mapping for autocomplete that is already working

```
MyModel.createMapping({
	"analysis" : {
		"filter": {
			"autocomplete_filter": {
				"type": "edge_ngram",
				"min_gram": 1,
				"max_gram": 20
			}
		},
		"analyzer": {
		    "autocomplete": {
		        "type": "custom",
		        "tokenizer": "standard",
		        "filter": [
		            "lowercase",
		            "autocomplete_filter" 
		        ]
		    }
		}
	}
}, function( err, mapping ) {

});
```

Thanks for you help!

**Comment by gsantome** [comment]
@guumaster do you know if i could force elastic search to save my Integer value like String? because this action is not working sid: {type: Number, es_indexed: true, es_type: "string"},

Thanks

**Comment by dwatts3624** [comment]
I've been trying to get mapping to work as suggested in the documentation.  The code posted by @gsantome is actually very helpful.  Thank you!  Of course, this library is awesome as well!  

Though I'm having no luck getting the mapping to register.  I've tried this multiple times in different ways per examples I've found -- even trying to register references to built in analyzers and map them to my fields.

Here's the error I get when I start the app:

```
{ [Error: [index_creation_exception] failed to create index]
  status: '400',
  message: '[index_creation_exception] failed to create index',
  path: '/items',
  query: {},
  body: '{"analysis":{"analyzer":{"autocomplete":{"type":"custom","tokenizer":"standard","filter":["lowercase","autocomplete_filter"]}}},"filter":{"autocomplete_filter":{"type":"edge_ngram","min_gram":1,"max_gram":20}}}',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"illegal_argument_exception","reason":"Custom Analyzer [autocomplete] failed to find filter under name [autocomplete_filter]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

And here's the relevant portions of my code:

```javascript
var ItemSchema   = new Schema({
    name : { type: String, index: true, es_indexed: true, es_analyzer: 'autocomplete' }
});

ItemSchema.plugin(mongoosastic);

var Item = mongoose.model('Item', ItemSchema);
Item.createMapping({
  'analysis' : {
    'analyzer':{
      'autocomplete':{
        'type':'custom',
        'tokenizer': 'standard',
        'filter':   [
          'lowercase',
          'autocomplete_filter'
        ]
      }
    }
  },
  'filter': {
    'autocomplete_filter': {
      'type':     'edge_ngram',
      'min_gram': 1,
      'max_gram': 20
    }
  },
},function(err, mapping){
    if(err) console.log(err);
});

module.exports = Item;
```

Any ideas on what might be happening here?  Should I just register the analyzers manually?
