### ISSUE TITLE
ERR : Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by aredo** [mongoosastic/mongoosastic#111]
@guumaster can you help me man, i got error when running mongosastic on my ap

<img width="1085" alt="screen shot 2015-09-30 at 11 53 36 pm" src="https://cloud.githubusercontent.com/assets/201664/10200100/9a2c8ce4-67ce-11e5-8d16-01705b8f5f50.png">

**Comment by gazsp** [comment]
Can you show us some code please and what you're trying to do? Thanks.

**Comment by Ikhtiyor** [comment]
Step to reproduce.
1. Open mongodb CLI in two tab or what ever you use
2. Remove document from mongodb from first tab
3. Try to remove same document from second tab.

And you will get error
TypeError: Cannot read property 'constructor' of null
    at Query.postRemove (node_modules\mongoosastic\lib\mongoosastic.js:578:28)

**Comment by PascalPflaum** [comment]
I got this error as well by calling Model.findOneAndRemove({'_id' : id} with an id that is not in mongodb.
mongoose handles this graceful, but the plugins postRemove functions requires a proper document and throws the error mentioned.

**Comment by NicolasDucom** [comment]
Hi everyone, 
Is there any new info concerning this issue ? Or is the only solution to use a standard FindById and a model.remove() afterwards ?
Thanks ;)

**Comment by realmike33** [comment]
@NicolasDucom It's still an issue, luckily it seems like you found a workaround.
