### ISSUE TITLE
Adding ref relations into elasticsearch 

### ISSUE THREAD

**Issue by gsantome** [mongoosastic/mongoosastic#113]
Hello, so this is my problem... I have a basic model where i have a user value... that user is a ref to another mongodb collection... so when i retrieve my object i made a .populate to get the user... now I want that user name inside elasticsearch because I want to search by the name of the user... this is possible? I searched a lot and i couldn't find a solution... some users said i need to make this but didn't work

```
MySchema.post('save', function( doc ) {
	
	doc.populate('user', function( err, doc ) {
		
		if( err ) {
			console.log(err);
			throw err;
		}

		doc.index(function( err, res ) {
				doc.emit('es-indexed', err, res);
		})

	})

});
```

**Comment by guumaster** [comment]
Currently it is not possible. Also, duplicated of #8.
