### ISSUE TITLE
Unable to remove item index

### ISSUE THREAD

**Issue by jonnadams** [mongoosastic/mongoosastic#114]
I saw the related post located at https://github.com/mongoosastic/mongoosastic/issues/96.

On save I am able to see the new item in the index right away, but I am unable to remove items from the index. Is there a way to force this?

``` javascript
        async.waterfall([
            function(callback){
              User.findById(userid, function (err, user) {
                if (user) {
                  return callback(null, user);
                }
                return callback({success: false, message: 'User cannot be deleted.'});
              });
            },
            function(user, callback){
              User.remove({_id: user._id}, function(err){
                if (err) {
                  return callback(err);
                }
                return callback();
              });
            },
        ], function(err){
          if (err) {
            return res.json(err);
          }
          return res.json({success: true, message: 'User deleted.'});
        });
```

**Comment by guumaster** [comment]
Unable how? Are you getting an error? In which callback?

**Comment by johannds** [comment]
I think what @jonnadams means is : when you remove a document through mongoose, it isn't removed from the index. I am seeing the same behaviour. Is this by design, or should Mongoosastic automatically keep indices in sync when removing Mongoose documents through Schema.remove()?

**Comment by isayme** [comment]
@jonnadams use `user.remove()` instead of `User.remove({id: user._id})`.

mongoosastic donot know which documents removed when you call `User.remove`, just same reanson with related issue https://github.com/mongoosastic/mongoosastic/issues/164
