### ISSUE TITLE
[Q] Does mongoosastic retries if there is any problem in a request?

### ISSUE THREAD

**Issue by willyaranda** [mongoosastic/mongoosastic#116]
The thing is that we are using the Bulk API.

On mongoosastic (https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L184-L202) the `bulkAdd` is where our documents are added to the bulk buffer.

When the buffer exceeds the maximum items length, it does a `schema.statics.flush();` call.

This call does not send any callback, so on the `flush` method in https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L515-L523 it is set a default function, which is `nop`, a no-operation.

Then, the underlying official client is called, with the no-operation callback.

And here comes the problem… if there is any problem on the request, like a timeout, a small hiccup on the server… the bulk data is lost, forever, as we do not track if the request has been correctly made.

Am I wrong? Is someone else seeing problems?

PS: I have not checked if the underlying client is doing some retries or not. So close as necessary.
PS2: If this is happening, I can happily commit to a patch.

**Comment by JasonMore** [comment]
@willyaranda I just noticed the bulk insert flush does not handle callback errors as well. I would expect a event to be triggered on the schema level ?

@guumaster are you familiar with internal mongoose eventing? I'm looking at it a little bit and it seems to have schema level eventing? I'm thinking about making a change for publishing an event on bulk inserting.

cc @johnculviner

**Comment by guumaster** [comment]
I'm not that much familiar with mongoose. I've started to maintain this plugin when i needed some bug fixing and new functionality. As you may see, there are lots of open issues yet. We may need more maintainers that use mongoose/mongoosastic more often than me.

**Comment by willyaranda** [comment]
@JasonMore we ended up creating our own `index` method, and `bulk` (where we do not want a cb for each document, but a event).

That said, I would love to help on this if someone find it useful, as I would like to contribute back to this library.

**Comment by johnculviner** [comment]
We are considering similar at this point and/or enhancing the library to expose the bulk insert cb (and associated errors). Stay tuned more digging tomorrow!

**Comment by JasonMore** [comment]
@guumaster I got events working on bulk with the following code. Its a bit rough so I was looking for feedback

```
  schema.statics.flush = function flush(inCb) {
    //var cb = inCb || nop;

    schema.emit('es-beforeBulk', bulkBuffer);
    esClient.bulk({
      body: bulkBuffer
    }, function(err, res) {
      if(err) return schema.emit('es-bulkIndexed-error', err, res);
      schema.emit('es-bulkIndexed', res);
    });

    bulkBuffer = [];
  };
```

```
productSchema.plugin(mongoosastic);

var Product = mongoose.model('Product', productSchema);

Product.schema.on('es-beforeBulk', function (buffer) {
	log.info('es-beforeBulk', buffer);
});
Product.schema.on('es-bulkIndexed-error', function (err, res) {
	log.error('es-bulkIndexed-error', err, res);
});
Product.schema.on('es-bulkIndexed', function (res) {
	log.info('es-bulkIndexed', JSON.stringify(res, null, 2));
});
