### ISSUE TITLE
parent-child mapping

### ISSUE THREAD

**Issue by japrescott** [mongoosastic/mongoosastic#117]
I was trying to implement the parent-child linking as described in the elasticdocs (https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html).

Is this possible with monoosastic? I assume I would need to overload the save function of mongoose which is beeing overloaded by mongoosastic itself and add an optional parent_id?

**Comment by voz** [comment]
@japrescott I was trying to do it, but it is not super clean and finished. Actually would be nice to get some feedback on the approach: https://github.com/voz/mongoosastic/commit/925e6435db5436f1c855d47cea739339ddac3f4e

**Comment by bartvanremortele** [comment]
Any chance parent-child is going to make it into mongoosastic? It's very powerful and can cover a lot of use-cases.

**Comment by Hamdy** [comment]
no updates on this?

**Comment by japrescott** [comment]
I have created a fork with the elastic 'parentKey' feature enabled. I am using it myself and it seems to be working good. If I don't find a problem, I will open a PR

for anyone interested; https://github.com/japrescott/mongoosastic

**Comment by sasos90** [comment]
@japrescott can you give me some example usage please?

**Comment by japrescott** [comment]
@sasos90 I added some documentation and an example usage to my repo https://github.com/japrescott/mongoosastic

**Comment by sasos90** [comment]
That's great!
What if you have more "foreign keys"?

**Comment by guumaster** [comment]
@japrescott are your test passing? I'm open to merge a passing PR
