### ISSUE TITLE
Document new feature  es_type of nested with es_fields

### ISSUE THREAD

**Issue by guumaster** [mongoosastic/mongoosastic#123]
#120 is a great feature, but it lacks proper docs.

**Comment by JasonMore** [comment]
@guumaster I'll work on that. Sorry :-D

**Comment by guumaster** [comment]
Not a problem, I've created the issue to remember pending work, that's all. Thanks for the additions!

**Comment by JasonMore** [comment]
lol sorry I thought I merged these all into one commit. Whoops

**Comment by isayme** [comment]
@guumaster close the issue refer #131
