### ISSUE TITLE
Mapping ignored unless you run .createMapping

### ISSUE THREAD

**Issue by flaska** [mongoosastic/mongoosastic#124]
Hello, I've spend a day of my time by trying to figure out why Mongoosastic is ignoring my fields mapping. I thought you can just specify ElasticSearch mapping in mongoose schema definition like documentation says:

``` javascript
var User = new Schema({
    name: {type:String, es_indexed:true}
  , email: String
  , city: String
})
User.plugin(mongoosastic)
```

But this is not true. You do need to execute .createMapping in order to persist "es_" fields.

Can we improve the documentation please? 

I think this is how it should look like:

``` javascript
var BookSchema = new Schema({
    title: {type:String, es_boost:2.0}
  , author: {type:String, es_null_value:"Unknown Author"}
  , publicationDate: {type:Date, es_type:'date'} 
}); 

var BookModel = mongoose.model('Book', BookSchema);
BookModel.createMapping();
```

**Comment by isayme** [comment]
closed refer #271
