### ISSUE TITLE
Indexing nested objects stopped working in version >3.3.2

### ISSUE THREAD

**Issue by jan-swiecki** [mongoosastic/mongoosastic#136]
Starting with version 3.4.0 I cannot index nested objects. Nested field is defined as below.

```
pictures: {
  type: [ProductImage.schema],
  required: true,
  es_indexed: true
}
```

I configure my model with:

```
ProductSchema.plugin(mongoosastic, {
  esClient: esClient
});
```

`pictures` field is absent in Elasticsearch index.

Tested with Elasticsearch versions 1.7.3 and 2.0

**Comment by agjs** [comment]
I confirm this bug since I work on the same team with Jan. It's either that we are doing something wrong but after rolling back to 3.3.2, it seams to work. Could you please verify that you have written tests for nested objects and confirm that they are passing :). Thanks

**Comment by guumaster** [comment]
Please, check this PR #120 and try to add the property `es_type: 'nested'` to your `pictures` schema definition and see if that fixes it.

**Comment by aryeharmon** [comment]
This bug still exists.

**Comment by aryeharmon** [comment]
still not working with `es_type: 'nested'`
