### ISSUE TITLE
Items not removed from index after .remove() call to Mongoose

### ISSUE THREAD

**Issue by johannds** [mongoosastic/mongoosastic#137]
Hi,

It looks like items aren't being removed from ES after I call .remove({_id: xxx}) on my Mongoose model. 

Where should I start looking for issues? I've waiting an hour and the record is still in ES but not in the DB.

As far as I can see, I'm correctly setting up the model. 

```
var elasticConnection = url.parse(process.env.BONSAI_URL);

    var elasticOptions = {
        host: elasticConnection.hostname,
        port: elasticConnection.port,
        auth: {
            username: elasticConnection.auth.split(':')[0],
            password: elasticConnection.auth.split(':')[1]
        }
    };

    CalendarEventSchema.plugin(mongoosastic, {
        host: elasticConnection.hostname,
        auth: elasticConnection.auth,
        port: 9200,
        protocol: elasticConnection.protocol === 'https:' ? 'http' : 'https',
        hydrate: false,
        hydrateOptions: {},
        bulk: {
            size: 1000,
            delay: 2000
        }
    });

    CalendarEvent = mongoose.model('CalendarEvent', CalendarEventSchema);
    CalendarEvent.createMapping();
```

When I delete an event in our Mongoose model, like so: 

```
CalendarEvent.remove(filter).exec(function(err, docs) {
// everything works fine here, no errors.
         });
```

The item is not removed from the ES instance. I can still find it when running a search.

What am I doing wrong? or is this an issue?

Kindly,
Johann

**Comment by johannds** [comment]
Any news on this?

**Comment by jackMoscovi** [comment]
Im facing the same problem, Looks like no one is helping :(

**Comment by michaek** [comment]
It looks like the implementation in [deleteByMongoId](https://github.com/mongoosastic/mongoosastic/blob/v4.0.2/lib/mongoosastic.js#L140) requires `_id` to be used as the filter for remove. Is that what you're passing?

The hook in [postRemove](https://github.com/mongoosastic/mongoosastic/blob/v4.0.2/lib/mongoosastic.js#L590) specifies a noop function as the callback for unindexing, so it would be pretty easy for errors to get lost. I'd imagine that would be the right place to start digging.

**Comment by isayme** [comment]
please see https://github.com/mongoosastic/mongoosastic#removing-a-document, this is known as expected~

**Comment by solutionstack** [comment]
I used the direct http call as a work around, so just do something similar to
` await  fetch('http://localhost:9200/index/type/doc_id', { method: 'DELETE', body:'' });`
