### ISSUE TITLE
Mapping generator maps full subdocuments

### ISSUE THREAD

**Issue by nvartolomei** [mongoosastic/mongoosastic#145]
Mapping Generator indexes full subdocuments, even if I explicitly create a `es_indexed` parameter for top level fields.

Is there a way to ignore indexes for subdocuments? I can't find any in current implementation.

I tried to find with a quick solution, but couldn't find any to fit in current recursive implementation of getMapping function.

Maybe first we should traverse entire model recursively, and then if we find a field with `es_indexed: true` map only fields marked as `es_indexed` otherwise do full mapping?

This looks like best solution for me.

Or change this line:

``` js
// Check if field was explicity indexed, if not keep track implicitly
if (value.es_indexed) {
  hasEsIndex = true;
} else if (value.type) {
  implicitFields.push(field);
}
```

into

``` js
// Check if field was explicity indexed, if not keep track implicitly
if (value.es_indexed) {
  hasEsIndex = true;
} else if (value) {
  implicitFields.push(field);
}
```

cc: @guumaster

**Comment by nvartolomei** [comment]
Looks like my proposal doesn't break tests too.

**Comment by glortho** [comment]
+1 this apparently fixes my issues too @nvartolomei @guumaster , where a plugin we're using -- mongoose-crate -- adds a nested icon property to the schema that prevents custom mapping from being applied properly.
