### ISSUE TITLE
Forwarding elasticsearch promises

### ISSUE THREAD

**Issue by DerekDomino** [mongoosastic/mongoosastic#149]
ElasticSearch node module's search methods supports promises (https://github.com/elastic/elasticsearch-js):

```
client.search({
q: 'pants'
}).then(function (body) {
  var hits = body.hits.hits;
}, function (error) {
  console.trace(error.message);
});
```

It would be great if mongoosastic follows the same convention: when no callback is provided, a promise is returned.

The ElasticSearch module is flexible enough to let the user customise the promise library he/she can use:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-defer

**Comment by mateusfreira** [comment]
+1

**Comment by juanpujol** [comment]
+1

**Comment by isayme** [comment]
duplicated with #68
