### ISSUE TITLE
Data is not deleted in elasticsearch after I deleted data in mongoose.

### ISSUE THREAD

**Issue by jackMoscovi** [mongoosastic/mongoosastic#155]
Is this a known issue?, because seems like there is no solution for this problem. Anyone can share their solution here? would be really awesome

**Comment by SkateFreak** [comment]
i encountered this issue too.
we do have ``` Model.search() ``` but we don't have ``` Model.remove() ```

for now i'm just using the rest api to delete data manually:

    fetch(`http://localhost:9200/games/game/${gameId}`, {
        method: 'delete'
    })
    .then(function (response) {
        return response.json();
    });

**Comment by michaek** [comment]
There is an `unIndex()` method on an instance that might be preferable to constructing your own request.

**Comment by SkateFreak** [comment]
@michaek can you please refer us to the docs of ```unIndex()```?
couldn't find it here:
https://github.com/mongoosastic/mongoosastic

**Comment by michaek** [comment]
I don't think it's documented. I learned of it from reading the source: https://github.com/mongoosastic/mongoosastic/blob/v3.6.0/lib/mongoosastic.js#L324

**Comment by SkateFreak** [comment]
@michaek i would appreciate if you helped me come up with the proper syntax to 'unIndex'.
indexing is wired to each save, and to search i just do:

    Model.search({
        query: {
            match: {
                ...
            }
        }
    }, function() {
        ...
    });

how do i write my unIndex command?
thabks

**Comment by michaek** [comment]
You might try something like this to start

```
Model.findOne({
    query: {
        match: {
            ...
        }
    }
}, function(instance) {
    instance.unIndex()
});
```

From the source, unIndex takes a callback function that will be invoked with an error as its only argument.

**Comment by isayme** [comment]
mongoose will support `Model` level `remove` hook (ref https://github.com/Automattic/mongoose/issues/3054), and then mongoosastic will try to auto remove documents when you do `Model.remove`.

Currently, you can unIndex like this:
````
var cursor = Model.find(conds).cursor()
cursor.on('data', function (doc) {
  doc.remove() // this will auto remove the document from ES~
})
````

**Comment by isayme** [comment]
@jackMoscovi this is known issue, and we have mentioned this problem in document [Removing a document](https://github.com/mongoosastic/mongoosastic#removing-a-document)
