### ISSUE TITLE
Is the 3.6.1 tag due to be released to npm?

### ISSUE THREAD

**Issue by michaek** [mongoosastic/mongoosastic#156]
It seems there's a 3.6.1 release on GitHub from a couple weeks ago, but npm only knows about version 3.6.0. Is that release being delayed intentionally? Thanks!

**Comment by juanpujol** [comment]
Any news? Thanks.

**Comment by michaek** [comment]
From conversaion on https://github.com/mongoosastic/mongoosastic/commit/46a882a6121ef630c60a930387a1da67c55beac2 I can see that it's been published now.
