### ISSUE TITLE
Problem with function_score

### ISSUE THREAD

**Issue by kevinr89** [mongoosastic/mongoosastic#157]
I have this:

---

var nota = new Schema({
    titulo: { type: String, es_indexed:true, es_boost:2.0 },
    tituloNota: { type: String, es_indexed:true, es_boost:2.0 },
    baja: { 
      type: Boolean, 
      es_indexed:true, 
      es_type: "boolean",
      es_cast: function(value){
        if (value === true) return true
        return false
      }, 
    },
    introHTML: { type: String, es_indexed:true, es_cast: escape.unescape },
    introNotaHTML: { type: String, es_indexed:true, es_cast: escape.unescape },
    textoHTML: { type: String, es_indexed:true, es_cast: escape.unescape },
    infoHTML: { type: String, es_indexed:true, es_cast: escape.unescape },
    fecha_c: { 
      type: Number, 
      es_indexed:true,  
      es_cast: function(value){
        return new Date(value);
      }, 
      es_type:'date'
    }
});

nota.plugin(mongoosastic, {hydrate:true, hydrateOptions: {lean: true}})

var ModelNota = mongoose.model('notas', nota, 'notas');

---

I want to search "text to find", and boost by date:

---

ModelNota.search(
  {
    "query": {
      "function_score": {
        "query": {
          "bool": {
            "must": [{
              "term": {
                "baja": "false"
              }
            }, {
              "query_string": {
                "query": "text to find"
              }
            }]
          }
        },
        "functions": [{
          "gauss": {
            "fecha_c": {
              "scale": "130w",
              "offset": "26w",
              "decay": 0.3
            }
          }
        }],
        "score_mode": "multiply"
      }
    }
  }
, function(err, results) {
    if (err) console.log(err)
    if (results) console.log(results)
    if (results && results.hits && results.hits.hits) console.log(results.hits.hits[0])
});

---

This search return:

---

"error": {
    "root_cause": [{
        "type": "query_parsing_exception",
        "reason": "unknown field [fecha_c]",
        "index": "notass",
        "line": 1,
        "col": 221
    }, {
        "type": "query_parsing_exception",
        "reason": "unknown field [fecha_c]",
        "index": "test",
        "line": 1,
        "col": 221
    }],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [{
        "shard": 0,
        "index": "notass",
        "node": "Etgp89XhRQeQLYLXi2i6OA",
        "reason": {
            "type": "query_parsing_exception",
            "reason": "unknown field [fecha_c]",
            "index": "notass",
            "line": 1,
            "col": 221
        }
    }, {
        "shard": 0,
        "index": "test",
        "node": "Etgp89XhRQeQLYLXi2i6OA",
        "reason": {
            "type": "query_parsing_exception",
            "reason": "unknown field [fecha_c]",
            "index": "test",
            "line": 1,
            "col": 221
        }
    }]
},
"status": 400
}

---

What am i doing wrong?

Mongoose: 4.1.8
Mongoosastic: 3.6.0

**Comment by Code-Crash** [comment]
Hi ,

Is there any way to do function score queries using this library?

Thanks
