### ISSUE TITLE
all data not insert to elasticsearch

### ISSUE THREAD

**Issue by himanshuoodles** [mongoosastic/mongoosastic#158]
please ... my all database data is not inserted to elasticsearch ... I have inserted 9 lakh data in mongodb and only 4 lakh record are inserted in elasticsearch .

**Comment by Alexandre-io** [comment]
Are you using elasticsearch verison 2.x ?

**Comment by himanshuoodles** [comment]
i am use elasticsearch 1.7 . Actually when working on node i have to insert 9 lakh record one by one . My mongodb showing 9 lakh record and elesticsearch showing less records .Pls help me what to do

**Comment by himanshuoodles** [comment]
url of downloads http://www.unixmen.com/install-elasticsearch-ubuntu-14-04/

**Comment by goddyZhao** [comment]
I met the same issue that when I use synchronize to index to es for an existing collection, only part of the data are indexed in es

**Comment by himanshuoodles** [comment]
now this is done . The problem was i have to bulk index
