### ISSUE TITLE
score for all results is 1

### ISSUE THREAD

**Issue by joshbedo** [mongoosastic/mongoosastic#159]
I have the following query and all the results return with the same score. Is their something i'm missing?

``` js
        User.search({
          filtered: {
            query: {
              range: {
                budgetMax: {
                  "lte": user.budgetMax,
                },
                budgetMin: {
                  "gte": user.budgetMin,
                }
              }
            },
            filter: {
              terms: {
                /**
                * locations need to be lowercase since the search is case-sensitive.
                **/
                searchLocations: result.user.searchLocations.map((loc) => {
                  return loc.toLowerCase();
                })
              }
            }
          }

        }, cb)
```

**Comment by Voyz** [comment]
Doesn't seem like it's your case, but I had the following problem:

My code was in the form of:

`
myModel.search({
  query:{
    match:{
      "nature": "tree"
    }
  }
}
`

Mongoosastic by default inserts that 'query' object on the top of the DSL hierarchy. Hence my elastic request ended up having `{query:{query{...` and resulted in almost-correct searches, yet whose score was always 1.

Maybe this is something that could be mentioned in the documentation?

**Comment by basiclaser** [comment]
@joshbedo if im not mistaken, you're performing a filter operation. Filter queries do not calculate score, they are just ' yes / no ' operations. Your ' larger than / less than / equal to ' logic is equally as black and white. Documents are either in that range or not, there is no score gradient.
