### ISSUE TITLE
Synchronize resets bulk settings

### ISSUE THREAD

**Issue by vincentvanderweele** [mongoosastic/mongoosastic#161]
Currently bulk settings are reset when `synchronize` is done:

``` javascript
stream.on('close', function onClose(pA, pB) {
  var closeInterval;
  closeValues = [pA, pB];
  closeInterval = setInterval(function checkInterval() {
    if (counter === 0 && bulkBuffer.length === 0) {
      clearInterval(closeInterval);
      close();
      bulk = false;  // <--- overwrite the global bulk here
    }
  }, 1000);
});
```

However, `bulk` is a global property that is set by the constructor. This implies that bulk indexing will not be used any more after calling `synchronize`.

I propose to fix this issue by caching the global `bulk` object at the start of `synchronize` and reset to that object in the end.

When fixing this, I propose to also do a functional addition: add a configuration option to `synchronize` to override the bulk settings for that synchronization only. I typically want to index during synchronization in bigger batches than during normal operation.

Since PR #153 already adds a configuration object to `synchronize`, I propose that I wait until that PR is merged and create a PR for this issue afterwards.

**Comment by DerekDomino** [comment]
PR #200 (follow-up of PR #153) has been merged.

**Comment by michaek** [comment]
Does it make sense to have one setting of bulk state? That seems like it could cause weird behavior if other methods are invoked while synchronize is running: some instructions could end up getting batched into a bulk call (with an immediate callback) while others, called just before or just after synchronize, would be sent immediately, leading to work being done "out of order".

**Comment by michaek** [comment]
I've created a PR to reset bulk properly. Rather than caching the current value of `bulk`, which could inadvertently reset bulk to a temporary value if synchronize is run concurrently, this leaves the value of `options.bulk` unchanged and resets to that when synchronize completes.
