### ISSUE TITLE
.update() doesn't properly translate to elastic data

### ISSUE THREAD

**Issue by nschloe** [mongoosastic/mongoosastic#164]
Mongoosastic does a great job syncing data between mongo and elastic when adding data.

However, when `update()`ing data with mongoose, e.g.,

``` js
yield mongoose.model('Car').update({_id: my_id}, {color: "blue"});
```

the changes aren't properly translated to corresponding Elasticsearch instance.

**Comment by michaek** [comment]
I would guess this is because mongoosastic's mongoose hooks are defined for "save" and "findOneAndUpdate", but not update. Are you running into the same problem using "findOneAndUpdate"?

**Comment by nschloe** [comment]
`findOneAndUpdate()` works fine; `update()`ing doesn't.

**Comment by isayme** [comment]
Just as @michaek metioned, mongoosastic use `save` and `findOneAndUpdate` hooks to **auto** sync document.

But if you update documents with `Model.update`, mongoosastic don't know which documents updated, so we cannot **auto** sync any documents.
