### ISSUE TITLE
{new: true} required for findOneAndUpdate() to work

### ISSUE THREAD

**Issue by nschloe** [mongoosastic/mongoosastic#166]
I just found comment https://github.com/mongoosastic/mongoosastic/pull/97#issuecomment-166586313 to say that when `findOneAndUpdate()`ing methods, the changes do _not_ get properly propagated to elastic _unless_ the option

```
{new: true}
```

is explicitly given. This is because by default, mongoose returns the old object. (A breaking change in 4.0.)

I rely on mongoose returning the old object here and there, so this is pretty much a deal-breaker for me.

**Comment by michaek** [comment]
If it didn't return the new object using `{new: true}`, then the old version of the document would be what's available in the hook to index into elasticsearch. Wouldn't the only alternative be to run another query inside the `findOneAndUpdate` hook to get the "current" value of the document? That would have its own problems: an extra query to mongo and opening the door to a race condition. It seems like mongoosastic relying on `{new: true}` may be right, at least by default, though it could make sense to optinoally enable a second query if new is false. Is that what you were thinking, @nschloe?

**Comment by nschloe** [comment]
> then the old version of the document would be what's available in the hook to index into elasticsearch

Is that so? I had been under the impression that the hook always retrieves the changed data, just like the MongoDB does. Perhaps then this is more of a Mongoose issue. @vkarpov15 What do you think?

**Comment by vkarpov15** [comment]
I'm not familiar with the internals of mongoosastic, but `findOneAndUpdate()` will return the document **before** updates are applied unless you specify `{ new: true }` in mongoose >= 4.0.0. This was a breaking change in 4.0 to be more consistent with the [mongodb node driver](http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#findAndModify) and the [mongodb server itself](https://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/), which both default to `new: false`.

**Comment by nschloe** [comment]
@vkarpov15 Thanks for the insight. Returning the old data is fine; I'm wondering about what the hook should receive. (For background, the issue here is that after a `findOneAndUpdate()`, Elasticsearch is fed with the old data, not with the new data that the MongoDB receives.)

**Comment by vkarpov15** [comment]
If you have a post `findOneAndUpdate()` hook, you'll get the old document unless you specify `{ new: true }`.

**Comment by nschloe** [comment]
Is there any way to retrieve the updated document from any of the hooks?

**Comment by michaek** [comment]
It would be possible to query the updated document in the hook, but that seems like something that you'd want to opt into to satisfy an edge case, rather than having it be the default behavior. For mongoosastic to work without changes, you'd definitely need `{new: true}` or you'd be indexing data from the last revision. I believe working with `{new: false}` would require either a change to mongoosastic (querying for the new document in the hook), or doing two updates - one to provide the old data that your current code requires, and another to index into elasticsearch.

**Comment by vkarpov15** [comment]
Yeah @michaek is right, if you don't use `new: true` you would have to run a separate query in the post hook.

**Comment by nschloe** [comment]
Is this a good thing, or something that should be though over?

**Comment by vkarpov15** [comment]
Even if we switch `new` to true by default (which I have no intention of doing because the [mongodb crud spec](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#find-and-modify) says its false by default), you'd still have the case where somebody might explicitly set `new: false` with mongoosastic and screw that up.

It would be pretty easy for you to create a `pre('findOneAndUpdate')` hook to set `new` to true for all calls to `findOneAndUpdate()` though.

**Comment by nschloe** [comment]
I thought more about making the hook value independent of whether `new` is `true` or `false`, but tying it to the value that actually gets written to the DB, i.e., always the `new` value.

**Comment by vkarpov15** [comment]
Not really possible, because the `new` value determines what gets sent to MongoDB, which then uses it to determine whether it should send back the document as it was before or after the updates were applied. Mongoose doesn't handle applying the updates, MongoDB does.

**Comment by nschloe** [comment]
>  because the `new` value determines what gets sent to MongoDB

I see. The `new` options maps to `new` of [MongoDB's own findAndModify](https://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/#db.collection.findAndModify). Not sure what the best thing to do is here.

**Comment by vkarpov15** [comment]
IMO the most seamless solution would be to have a `pre('findOneAndUpdate')` middleware that sets `new` to true unless the user has explicitly set it. You could also document this and rely on the user to do the right thing - I think most elasticsearch users want to use `new: true` anyway. The primary use case for `new: false` is things like distributed locking and coordinating jobs between multiple processes, and I can't think of any use case where you want to pull your distributed lock collection into elasticsearch.

**Comment by bartvanremortele** [comment]
I think adding this to the main README would be a good thing until there is a clear stance on this or a solution is provided. It took me some time to figure out what was going wrong. Might help others if it's in a FAQ section or something similar.

**Comment by isayme** [comment]
closed. since this is the way mongoosastic work.
