### ISSUE TITLE
status is string?

### ISSUE THREAD

**Issue by nschloe** [mongoosastic/mongoosastic#167]
I see that mongoosastic returns strings in the `status` field, e.g.,

```
{ [Error: Not Found] status: '404', message: 'Not Found' }
```

Shouldn't this always be an `int`?

**Comment by isayme** [comment]
@nschloe how can we reproduce the error? I think it's from elasticsearch~
I tried, but got a `Number` type status.

**Comment by nschloe** [comment]
Probably fixed upstream. Closing.
