### ISSUE TITLE
documentation for esTruncate wrong

### ISSUE THREAD

**Issue by nschloe** [mongoosastic/mongoosastic#168]
[The documentation for `esTruncate()`](https://github.com/mongoosastic/mongoosastic#truncating-an-index) says

```
GarbageModel.esTruncate(function(err){...});
```

but really it should be

```
GarbageModel.esTruncate({}, function(err){...});
```

see https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L372.

**Comment by isayme** [comment]
@guumaster @nschloe we can close this issue since the first parameter of esTruncate is optional~
