### ISSUE TITLE
I want to search element according to price and categories name ?

### ISSUE THREAD

**Issue by himanshuoodles** [mongoosastic/mongoosastic#173]
how can i search a documents by price and its name in mongoosatic

**Comment by guumaster** [comment]
please give more details, the question is too vague. re-open with schema and what are you trying

**Comment by himanshuoodles** [comment]
This is my model and and i want to search according to categoriesName and amount . what type of query to apply

var ProductsSchema= new mongooseSchema({
    
    categoriesName:{
        type: String,
		default: '',
		index:true,
		required: true,
		trim: true,
        validate: [stringNotNull, "categories name is required."],
         es_indexed:true
    },
	 categoriesId:{
        type: String,
		default: '',
		index:true,
		required: true,
		trim: true,
        validate: [stringNotNull, "categories id is required."],
          es_indexed:true
    },
	ProductId: {
		type: String,
		ref: 'ECommerceCategories',
		default: '',
		index:true,
		required: true,
		trim: true,
        validate: [stringNotNull, "ProductId name is required."],
         es_indexed:true
	}, 
	
    productAttributes:{
            title:  {
                type: String,
                default: '',
		        required: true,
                trim: true,
                validate: [stringNotNull, "productAttributes name is required."],
                es_indexed:true
	           },
	
        imageUrls: {
                "400x400": {
		            type: String,
		            default: '',
		            required: false,
		            trim: true,
        
	         }
        
              },
        sellingPrice: {
            amount:{
		            type: String,
		            default: '',
		            required: false,
		            trim: true,
        
	                },
            currency: {
		            type: String,
		            default: '',
		            required: false,
		            trim: true,
        
	                }
          }
    
    }
    
});
ProductsSchema.plugin(mongoosastic,{
   hosts: [
   '127.0.0.1:9200'
      
  ]
});
