### ISSUE TITLE
The _id field of populated documents is not indexed

### ISSUE THREAD

**Issue by michaek** [mongoosastic/mongoosastic#175]
The condition [`if (prefix === '' && (field === 'id' || field === '_id')`)](https://github.com/mongoosastic/mongoosastic/blob/v4.0.2/lib/mapping-generator.js#L130) prevents the `_id` field of populated document references from being indexed. I'm not sure from reading the source what purpose that line serves, and how I would safely make a change to permit the indexing of `_id` fields. Can you explain or help point me in the right direction? Thanks!

**Comment by michaek** [comment]
Can anyone shed some light here? This line doesn't seem beneficial, and I'd really like to understand the reasoning behind it.

**Comment by KPouianou** [comment]
I have the same issue. I could imagine cases where checking for _id might be beneficial, but what is the point of field === 'id'?

**Comment by michaek** [comment]
Looks like this has been reported again as #215

**Comment by davidwu226** [comment]
I have a patch that fixes this in #216.

**Comment by michaek** [comment]
Before there's a fix for this, it seems worthwhile to learn what the maintainers intended for this feature. From my perspective, it seems the entire conditional could be removed, but I don't want to jump to conclusions. @guumaster, it seems like you're most likely to have some insight into this?

**Comment by ReactJSRecruitmentTest** [comment]
Any word on this? Has it been resolved? @guumaster

**Comment by charliedavison** [comment]
Any word on this? Has it been resolved? @guumaster
