### ISSUE TITLE
pagination in flitter 

### ISSUE THREAD

**Issue by himanshuoodles** [mongoosastic/mongoosastic#176]
"filtered": {
         "query": {
            "match_all": {}
             
         },
         "filter": {
           "bool": {
             "must": [
               {
                  "term": {
                     "categoriesId": "56bd8238a6fdaebf168c7d29"//item
                  }
               },

                {
                   "range": {
                      "amount": {
                        "gte" : results.minprizeRange
            
                         
                      }
                   }
                }
             ]
           }
         }
      }

**Comment by guumaster** [comment]
Is this a question?  What do you need? Please explain and re open

**Comment by himanshuoodles** [comment]
hello sir I want to appy pagination on filter like i want 10 element one time then next 10 then next 10 . How can it will we possible
