### ISSUE TITLE
decouple repo from taterbase/mongoosastic

### ISSUE THREAD

**Issue by nschloe** [mongoosastic/mongoosastic#180]
Forking repositories is great because it gives credit to the original author and thus somehow preserves history beyond the Git history.

There are some disadvantages to it, too, though. For example, One cannot search in forked repositories on GitHub. It'd thus suggest to decouple `mongoosastic/mongoosastic` from `taterbase/mongoosastic`. – Briefly contacting GitHub would get the job done.

**Comment by guumaster** [comment]
I'd like this too. @taterbase would you like to do this?

**Comment by guumaster** [comment]
Done
