### ISSUE TITLE
how to use populate option with objectIdArray?

### ISSUE THREAD

**Issue by youngerheart** [mongoosastic/mongoosastic#181]
```

const EduExperienceSchema = new Schema({
    dateStart: Date,
    dateEnd: Date,
    collage: String
});

const ResumeSchema = new Schema({
    eduExperience: [{
        type: Schema.Types.ObjectId,
        ref: 'EduExperience',
        es_schema: EduExperience
    }]
});


ResumeSchema.plugin(mongoosastic, {
    populate: [{path: 'eduExperience'}]
});
```

and I get

```
{
    "eduExperience": [
        { }
        ,
        { }
        ,
        { }
    ]
}
```

in Elasticsearch,

```
{
eduExperience: [
{
_id: "56cbf4a0ffa4863e0ee1ee6f",
collage: "sddsffds",
__v: 0
},
{
_id: "56cc0480cea1eeb911d06615",
collage: "123",
__v: 0
},
{
_id: "56cc067a2c156ee01148e9fe",
collage: "123",
__v: 0
}
]
}
```

in mongo

when I not use populate option,  Elasticsearch return only a _id first，after push another eduExperience，then first record shows the collage field but the last still not

when I update eduExperience data (mongoose `save` method), Elasticsearch doesn't update

what's wrong?I have wasted two day for this problem @evindor @nvartolomei thank you.

**Comment by isayme** [comment]
@youngerheart please upgrade to 4.2.2. and modify `es_schema: EduExperience` to `es_schema: EduExperienceSchema`, things will be ok.
