### ISSUE TITLE
Detach fork from taterbase repo

### ISSUE THREAD

**Issue by andrenarchy** [mongoosastic/mongoosastic#183]
It'd be great if the mongoosastic repo is detached from the taterbase repo. Otherwise, this repo is not considered a full repo and some github features are not available (e.g., code search).

@guumaster you can contact the friendly github support to detach the fork, see also [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)

**Comment by guumaster** [comment]
Thanks, I've submitted a request to detach it. Lets wait and see if they do it.

**Comment by guumaster** [comment]
done!

**Comment by andrenarchy** [comment]
thx!
