### ISSUE TITLE
Searching immediately after indexing requires a timeout

### ISSUE THREAD

**Issue by SkateFreak** [mongoosastic/mongoosastic#186]
I have an api endpoint for posting data to mongoose.
I try to perform a search immediately after and i get 0 results. the code:

```
newSchema.save((err) => {
    if (err) reject(new Error(err));
    newSchema.on('es-indexed', (err, res) => {
        Schema.search(query, function (err, results) {
            resolve(results);
        });
    });
});
```

My **hits** return empty.
If i surround `Schema.search` with a timeout of **1000ms** i get the results.

I don't wanna use this timeout workaround. Anybody have a suggestion?
Thanks.

**Comment by Jabsouliman** [comment]
I have the same problem.

**Comment by isayme** [comment]
@SkateFreak @Jabsouliman duplicate with https://github.com/mongoosastic/mongoosastic/issues/253
