### ISSUE TITLE
Trying to do spanish stemming

### ISSUE THREAD

**Issue by aletorrado** [mongoosastic/mongoosastic#189]
Hi, this is a newbie question: I'm failing to properly configure mongoosastic to do stemming on spanish words (with accents).

I'm doing this:

```
var mySchema = Schema({
...
bodyText: { type: String, es_indexed: true, es_boost: 1, es_analyzer: 'testtt' },
...
});

var model = mongoose.model('Article', mySchema);
```

```
model.createMapping({
    analysis: {
        analyzer: {
            testtt: {
                tokenizer: "standard",
                filter: ["standard", "asciifolding"]
            }
        }
    }
},function(err, mapping){
    console.log(err, mapping)
});
```

What's wrong? Thanks!

**Comment by basiclaser** [comment]
I'm having a similar issue, asciifolding does not seem to be happening for me either. My code is the same.

**Comment by danielstaleiny** [comment]
If it doesn't work you can call api directly and create mapping. Once you have mapping just use that index to store document there. I think one of the issue could be conflict on creating same index which is already created.  This can happen especially when you use mongoosastic in script,server, init files. Make sure you your index is not created. 

documentation [example](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/algorithmic-stemmers.html) 
and your standard filter does nothing [doc](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/analysis-standard-tokenfilter.html)
