### ISSUE TITLE
Match all and filters

### ISSUE THREAD

**Issue by michelem09** [mongoosastic/mongoosastic#191]
Hello I have a code like this:

```
var queryOptions = {};
var query = {
       match_all: {}
};
var filterPublished = {
       term: {
            publishingStatus: '04'
        }
};

queryOptions.filter = filterPublished;

Catalog.search(query, queryOptions, function(err, products) {
  // Products have publishingStatus !== 04
}
```

This should filter items with publishingStatus !== 04 but it doesn't happen.

While in the same ES if I do a query like this, it works correctly and it should be the same I build with Mongoosastic (code above):

```
{
    "query": {
        "match_all": {}
    },
    "filter": {
        "term": {
                        "publishingStatus": "04"
                }
    }
}
```

Any idea?

**Comment by michelem09** [comment]
I solved it with a query like this:

```
filtered: {
	query: {
		query_string: {
			analyze_wildcard: true,
			query: '*',
			use_dis_max: true
		}
	},
	filter: {
		term: {
			publishingStatus: '04'
		}
	}
}
```

But I think there is a problem with the filter option in Mongoosastic, because it want work with any query.

So you can't use a `filter`as option in a search like that one I posted before.

**Comment by alqamabinsadiq** [comment]
I am facing the same issue I can't match a term. In Kibana's DevTool everything is working fine but when I am passing the same query in search of Mongoosastic it's not working.

**Comment by alqamabinsadiq** [comment]
Passing this in search function
```
query_string: {
        analyze_wildcard: true,
        query: '*',
        use_dis_max: true
      }
```
Returns all the documents.
