### ISSUE TITLE
Synchronise may break mappings

### ISSUE THREAD

**Issue by Voyz** [mongoosastic/mongoosastic#199]
I use synchronise functionality often to keep my indices synced.

I noticed during tests that after clearing an index and synchronising it, if I don't create mappings for my numeric types explicitly (it happens automatically if property types are not pre-defined on synchronising) the range queries don't work.

Trying to figure out how do the mappings are executed using a script I was getting 
`No field found for [height] in mapping with types []`

The solution is to define all property types while doing initial mapping so that synchronise uses these pre-defined types.

Not sure if that's a bug or expected, but may help someone

**Comment by cakuki** [comment]
elasticsearch mappings are immutable, so yes you have to define all properties with types initially.

**Comment by isayme** [comment]
@Voyz you have to call `createMapping` manually before indexing any document.
