### ISSUE TITLE
Call createMapping on model if no mapping exists

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#2]
https://github.com/jamescarr/mongoosastic/issues/62#issue-12952361

>Not sure if this is possible, would be nice to do if it is though.

**Comment by andrewmcwatters** [comment]
Is this still an issue? I'm having some `geo_point` problems at the moment, and don't know if it might be related to this or not.

I'm willing to submit a pr to resolve if it is. Please give me a heads up when you're able!

**Comment by guumaster** [comment]
@andrewmcwatters, latests PR solved this. Try version ^3.1.2, and if the problem still persist, create a new issue with code example
