### ISSUE TITLE
es_cast not working

### ISSUE THREAD

**Issue by iq-dot** [mongoosastic/mongoosastic#201]
Hi guys,

I have an issue where it seems like es_cast is not being used or executed.

I have this:

```
favourites: {
  type: [String]
  es_type: 'integer',
  es_cast: function (val) {
    return val.length;
  }
}
```

Basically trying to return the length of the array then the array itself however I get the array being sent.

I also tried to explicitly create field in elastic search by setting its type to integer. Not sure if there is anything else I am missing or if this is a bug.

**Comment by isayme** [comment]
@iq-dot you need add another option: `es_indexed: true`
