### ISSUE TITLE
_count API

### ISSUE THREAD

**Issue by gormat** [mongoosastic/mongoosastic#204]
How can I use _count API? for just counting objects and dont get them.

**Comment by maksymseleznov** [comment]
+1

**Comment by maksymseleznov** [comment]
schema.statics.esCount = function esCount(inQuery, inCb) {
    var cb = inCb,
      query = inQuery,
      esQuery;

    setIndexNameIfUnset(this.modelName);

    if (!cb && typeof query === 'function') {
      cb = query;
      query = null;
    }

    esQuery = {
      body: {
        query: query
      },
      index: indexName,
      type: typeName
    };

    esClient.count(esQuery, cb);
  };

**Comment by gormat** [comment]
ok I added something like this on module :D Thank you
