### ISSUE TITLE
Update elasticsearch to v11+ to solve promise-js bug.

### ISSUE THREAD

**Issue by iq-dot** [mongoosastic/mongoosastic#206]
There is a bug on all elastic search versions 10+ that gives you a 'Symbol.iterator' cannot be redefined error. This is fixed on v11+.

I am encountering this issue and having to manually override this.

**Comment by isayme** [comment]
@guumaster, we can close this issue refer https://github.com/mongoosastic/mongoosastic/commit/1c139deee5f988a8095b684f32bd64e49a50fe06
