### ISSUE TITLE
Error: [illegal_argument_exception] mapper [category] of different type, curren t_type [string], merged_type [ObjectMapper]

### ISSUE THREAD

**Issue by nairicode** [mongoosastic/mongoosastic#210]
I have a database of inside 60 items, 
but it populate not work with createMapping,
i have this error and this code

![image](https://cloud.githubusercontent.com/assets/15065065/14983121/271c4e2e-114c-11e6-8940-5d5cbfae5f96.png)

`var mongoose = require('mongoose');
var secret = require('./config/secret');
var mongoosastic = require('mongoosastic');
var Schema = mongoose.Schema;

mongoose.connect(secret.database, function(err){
  if(err)
    throw err;

  console.log('Connected to the database.');
});

var CategorySchema = new Schema({
  name:{type: String, unique: true, lowercase: true}
});
var Category = mongoose.model('Category', CategorySchema);

var ProductSchema = new Schema({
  category:{type: Schema.Types.ObjectId, ref: 'Category',
    es_schema: Category, es_indexed:true, es_select: 'name'},
  name: String,
  price: Number,
  image: String
});

ProductSchema.plugin(mongoosastic, {
  hosts: [
    'localhost:9200',
    'anotherhost:9200'
  ],
  populate: [
    {path: 'category', select: 'name'}
  ]
});

var Product = mongoose.model('Product', ProductSchema);

Product.createMapping(function(err, mapping){
  if(err)
    throw err;

  console.log('Mapping created');
  console.log(mapping);
});

var stream = Product.synchronize();
var count = 0;

stream.on('data', function(){
  count++;
});

stream.on('close', function(){
  console.log('index: ' + count);
});

stream.on('error', function(err){
  console.log(err);
});
`

**Comment by isayme** [comment]
I think you have existing mapping with field `category` as `string` type.
try to remove existing mapping and try again.

**Comment by Sundin** [comment]
How would I remove an existing mapping like you suggest @isayme?

**Comment by isayme** [comment]
@Sundin remove the index. https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-delete-index.html
