### ISSUE TITLE
ES7 (async/await)

### ISSUE THREAD

**Issue by hoodsy** [mongoosastic/mongoosastic#217]
Would it be possible to support async/await for elastic search queries?

Not sure how to achieve this, maybe by wrapping the query [using co](https://github.com/tj/co).

**Comment by nvartolomei** [comment]
You can wait for #150, after this you will be able to `await` calls to `Model.search`. Or you could wrap them into something like [`bluebird.promisify`](http://bluebirdjs.com/docs/api/promise.promisify.html#promise.promisify).

**Comment by hoodsy** [comment]
Ok that will b perfect. I wrapped it with a promise and it works nicely.

**Comment by isayme** [comment]
closed.
please keep eye on the progress of https://github.com/mongoosastic/mongoosastic/issues/68~
