### ISSUE TITLE
esSearch method missing from NPM releases

### ISSUE THREAD

**Issue by bartvanremortele** [mongoosastic/mongoosastic#219]
I'm currently using mongoosastic version 4.0.2 and I seem to be missing the esSearch method in the published NPM package. I just looked at the repository here and in the source it's there and the package.json version is 4.0.1. According to the date of the 4.0.2 release the current master hasn't been published to NPM yet, is this correct? When will the new release be published? Thanks.

**Comment by jestersimpps** [comment]
also not in 4.0.1

**Comment by oddoye-david** [comment]
+1

**Comment by qimuxi1990** [comment]
@bartvanremortele if you only need to paginate result, use options in search() may be an alternative solution. See #46

**Comment by isayme** [comment]
@guumaster close this issue please, `esSearch` is added since `v4.1.0`.
