### ISSUE TITLE
i have indexes some fields in elasticsearch, now i would like to create more indexes. so what should i do now? Is there any script to update autometically?

### ISSUE THREAD

**Issue by samseralam** [mongoosastic/mongoosastic#224]
Note: i have applied es_indexed in one field and more than 4 lac records saved in elasticsearch, now i want to aply es_indexed in more field.
so what should i do now? i should delete all previous records or is there any script to reflect es_indexed in all saved records. here is my schema....

var ProductsSchema= new mongooseSchema({

```
categoriesName:{
    type: String,
    default: '',
    index:true,
    required: true,
    trim: true,
    validate: [stringNotNull, "categories name is required."],
    es_indexed:true
},
 categoriesId:{
    type: String,
    default: '',
    index:true,
    required: true,
    trim: true,
    validate: [stringNotNull, "categories id is required."]

},
ProductId: {
    type: String,
    default: '',
    index:true,
    required: true,
    trim: true
}, 
 sellingamountPrice: {
     type: Number,
    default: 0,
    required: false,
    trim: true
 }
```

})

**Comment by isayme** [comment]
@samseralam you can try `synchronize` to reindex existing documents. 
please refer [Indexing An Existing Collection](https://github.com/mongoosastic/mongoosastic#indexing-an-existing-collection) for more document.
