### ISSUE TITLE
Expected Synchronize() Behavior

### ISSUE THREAD

**Issue by danielmeng07** [mongoosastic/mongoosastic#226]
I'm not very familiar with Mongoosastic, but I'm observing some odd behavior. 

Schema with `es_index`

```
var userSchema = new mongoose.Schema({
    _sid           : { ... }
  , library        :  { ... }
  ... // other stuff
  , profile        : {
      displayName : { type : string, es_index : true } 
  }
})
```

Synchronize: 

```
var user = mongoose.model('user', userSchema)
  , stream = user.synchronize()
  , count = 0;

stream.on('data', function(err, doc){
  count++;
});
stream.on('close', function(){
  console.log('indexed ' + count + ' documents!');
});
stream.on('error', function(err){
  console.log(err); 
});
```

It's printing out this error for every document, even though this field is not suppose to be included:

`MapperParsingException[failed to parse [notifications.date]]; nested: NumberFormatException[For input string: \"06/29/2016\"];`

It is also logging the entire document, with all the other fields that do not include `es_index`. When I go to my `localhost:9200/users/user/_search`, it displays the entire collections - values and all. 

I was expecting each document to have one field, in this case, `user.profile.displayName`. 

What is the expected behavior?

**Comment by isayme** [comment]
@danielmeng07 I think you really want `es_indexed` not `es_index`.

if your do mean `es_index`, do it like `es_index: 'analyzed'`

see https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-index.html
