### ISSUE TITLE
how to set elasticsearch custom analyzer?

### ISSUE THREAD

**Issue by usemodj** [mongoosastic/mongoosastic#229]
how to set analyzer if custom analyser is 'analysis-icu'.

**Comment by tsturzl** [comment]
You can pass a custom analyzer if you create a mapping on demand, see [here](https://github.com/mongoosastic/mongoosastic#creating-mappings-on-demand)

**Comment by isayme** [comment]
@usemodj plz reopen this issue if have more question.
