### ISSUE TITLE
Mongoose deprecation warning for Query.prototype.stream()

### ISSUE THREAD

**Issue by fshort** [mongoosastic/mongoosastic#230]
Getting the following warning when using mongoose >= 4.5.0 and mongoosastic latest:

> Mongoose:Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead

Is there a planned fix for this?

**Comment by Parveenchauhan** [comment]
I was also facing the same issue, so first I upgrade the mongoose version in   "mongoose": "4.5.8" then  I use the cursor as query.cursor () were previously using query. stream ().

Now I am not getting the same warning and its working fine.

**Comment by fshort** [comment]
I'm not calling query.stream() but am calling Model.synchronize() to sync an existing collection with ES. Looking at the latest mongoosastic code, the synchronize function is calling stream():

`stream = this.find(query).batchSize(bulk.batch).stream();`

**Comment by Parveenchauhan** [comment]
For your reference here is some solution : - 
http://stackoverflow.com/questions/35650017/mongoose-model-aggregate-stream

according to this you have to change your query like : -

stream = this.find(query).cursor({ batchSize: 100 }).exec();

Hope so this will help you.

**Comment by inolasco** [comment]
Having the same warning. The `synchronize` function needs to be updated to use cursors instead of streams.

**Comment by SargoDarya** [comment]
This has been open for quite a while, is there a fix for this already?

**Comment by isayme** [comment]
@guumaster please close this issue refer #243
