### ISSUE TITLE
Integration with KeystoneJS

### ISSUE THREAD

**Issue by poeyer** [mongoosastic/mongoosastic#232]
I'm having issues with indexing a reference (https://github.com/mongoosastic/mongoosastic#indexing-mongoose-references) in KeystoneJS.

Normally referencing with an objectId should work but this is not allowed in KeystoneJS as it is not a 'valid' Keystone Type. When trying to populate the relationship I'm only indexing the objectId of the relationship. 

Is this even possible?

**Comment by supercycle91** [comment]
@poeyer Any luck with this? Stuck in the same spot..

**Comment by whnunlife** [comment]
@poeyer I'm having the same issue, I can't get objectID relationships to be index. Has anyone found a solve?

**Comment by poeyer** [comment]
@supercycle91 @whnunlife instead of using mongoosastic, I used the elasticsearch package and work with the post save hook.

`Brand.add({
    name: {
        type: String,
        required: true
    },
    isHighlighted: {
        type: Boolean
    },
    slogan: {
        type: String
    },
    file: {
        type: Types.S3File
    }
});

var hook = elasticHooks.init('brand');
Brand.schema.post('save', function() {
    // this represents the saved data
    // I save it manually in elasticsearch, makes it lot easier to play with it
    hook.save(this, Brand.model);
});`

**Comment by whnunlife** [comment]
@poeyer This package? https://www.npmjs.com/package/elasticsearch

**Comment by ShibaniMahapatra** [comment]
Hey @whnunlife can you confirm on this? And also it would be really great if you could share some code example for the same. I am trying to insert data in MongoDb and Elastic at the same time and search the same using Elastic. I am not sure if that is possible in Keystonejs. Thanks in advance. :)
