### ISSUE TITLE
Indexing mongoose references---cannot get populated data when doing Model.search()

### ISSUE THREAD

**Issue by jwzh222** [mongoosastic/mongoosastic#234]
var Comment = new Schema({
    title: String
  , body: String
  , author: String
});
var User = new Schema({
    name: {type:String, es_indexed:true}
  , email: String
  , city: {type:String, es_indexed:true}
  , comments: {type: Schema.Types.ObjectId, ref: 'Comment',
    es_schema: Comment, es_indexed:true, es_select: 'title body'}
})

User.plugin(mongoosastic, {
  populate: [
    {path: 'comments', select: 'title body'}
  ]
})

our data:
User1: city:A  (ref)comments:{title: 'sad'}
User2: city:A  (ref)comments:{title: 'happy'}
User3: city:B  (ref)comments:{title: 'happy'}

my question:
how can i use es search to get data by this condition: city=A and title='happy'

/api/1.js:
My trying:
But the result of this script lost comments field, how can i populate comments and filter the title field?
User.search({
        query: {
            bool: {
                should: [{match: {city : 'A'}}]
            }
        }
    }, 
        (err,results)=>{
            if(err) console.log(err);
        res.send(results);
    });

Is there anything wrong with my way to doing this ? please help me out

**Comment by isayme** [comment]
use `must` instead of `should`, refer: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

````
User.search({
  bool: {
    must: [{
      match: {
        city : 'A'
      }
    }, {
      match: {
        'comments.title': 'happy'
      }
    }]
  }
}, callback)
````
