### ISSUE TITLE
synchronize() against direct modification on mongoDB

### ISSUE THREAD

**Issue by qimuxi1990** [mongoosastic/mongoosastic#238]
Hi, I recently meet an issue:
I have a collection in mongo, and I use synchronize() to synchronize it into ES. It works fine.
However, it happened that I have to operate directly on mongoDB (using mongo shell) to remove one doc in this collection, (since delete doc is not allowed in my nodejs app). So ES did not follow this operation and the doc should be removed remained in ES. 
I stopped my app and restarted it, synchronize started again, but did not remove the deleted doc from ES.
My current solution is remove the entire index from ES and restart my app, so the synchronize() will push all documents into ES as expected. 

I am wondering if there is a better solution, due to the fact that synchronize() would cost a longer time if my collection grows larger. Anyone can help?

**Comment by isayme** [comment]
HI @qimuxi1990 , mongoosastic cannot handle your problem, but there do another solution~

please try https://github.com/elastic/sense, and then you can manage your indexed documents with simple RESTful API.
