### ISSUE TITLE
Looking for maintainers 

### ISSUE THREAD

**Issue by guumaster** [mongoosastic/mongoosastic#240]
We have lots of issues that need review/fixes. I'm not doing any Node or Elasticsearch at the moment, so is hard for me to keep working on this. If there are any volunteer to check issues and keep evolving this, reply or mention me on twitter @guumaster.

**Comment by conglq** [comment]
Hi! I'm using your module. I'm glad to improve mongoosastic.

**Comment by SargoDarya** [comment]
Would also like to contribute in a meaningful way.

**Comment by thebigredgeek** [comment]
I'd love to help maintain the project.  I use mongoosastic quite heavily

**Comment by guumaster** [comment]
@thebigredgeek, @SargoDarya @conglq If you'd like to help, try browsing the issues, comment and make PRs.

**Comment by isayme** [comment]
Hi, @guumaster , I'v glad to be one of the maintainers~

**Comment by guumaster** [comment]
Thanks all volunteers. You can start by browsing the issues, answer or ask for clarification, see if they are still relevant or need close. And of course, make PR, I'll add active collaborators as maintainers.

**Comment by guumaster** [comment]
Anyone who still want to join, follow @isayme example. Closed dozens of issues and made great PRs! Thanks!

**Comment by danielstaleiny** [comment]
@guumaster 
can you create develop branch so I can create pull request to it ?

**Comment by guumaster** [comment]
You can create PRs directly to master. We are not following any specific flow.

Add WIP: on the title if you like to discuss or show anything before merging

**Comment by muhammadfaizan** [comment]
I can help with it, i am currently using it. and need support to add date formatting

**Comment by guumaster** [comment]
I've made a new public request for maintainers. The main issue is to get the tests passing with the updated deps. 

I'm closing this in favor of #457
