### ISSUE TITLE
Error: No Living connections

### ISSUE THREAD

**Issue by nikitabanthiya** [mongoosastic/mongoosastic#242]
error creating mapping
{ [Error: No Living connections] message: 'No Living connections' }
Connected to the database
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Indexed90documents

**Comment by Mattchewone** [comment]
Can you share your mapping? 

The no "No Living connections" looks like a connection to Elasticsearch cannot be made.

**Comment by rodrigogs** [comment]
I have this error when I pass host instead of esClient:

Works:
```javascript
    const esClient = new elasticsearch.Client({
        host: process.env.ELASTICSEARCH || 'localhost:9200'
    });
    const getConfig = options => {
        return _.merge({
            esClient: esClient
        }, options || {});
    }
```

Fails:
```javascript
    const getConfig = options => {
        return _.merge({
            host: process.env.ELASTICSEARCH || 'localhost:9200'
        }, options || {});
    }
```

Shouldn't it have the same behavior in both cases?

**Comment by isayme** [comment]
@nikitabanthiya @rodrigogs you should not add `port` when using host, add another `port` option~

**Comment by rodrigogs** [comment]
Documentation must be fixed then...

**Comment by guumaster** [comment]
Sure, we welcome PR contributions :wink:
