### ISSUE TITLE
Missing 4.0.2 commit

### ISSUE THREAD

**Issue by joeferner** [mongoosastic/mongoosastic#244]
I see the tag for 4.0.2 and I see 4.0.2 is the latest release on npm but I don't see a commit on package.json for 4.0.2.

https://github.com/mongoosastic/mongoosastic/commits/master/package.json

Also any chance of publishing a new release 4.0.3

**Comment by guumaster** [comment]
I'll try to do it this weekend.

**Comment by guumaster** [comment]
done.
