### ISSUE TITLE
Analyzer for a field type is ignored

### ISSUE THREAD

**Issue by iq-dot** [mongoosastic/mongoosastic#25]
Hi Guys,

I am trying to define a specific analyzer for some field types however it is being ignored, I am following the convention of prefixing 'es_' to fields types that map to the elasticsearch mapping configuration.

Example:

```
var MyModel: {
  field: {
    type: string,
   es_indexed: true,
   es_analyzer: 'my_analyzer'
  } 
}
```

I have also tried prior to running the app, to set-up the index myself manually to make sure my custom analyser is available but still the mappings don't have it.

For now, I am having to manually use the REST API to delete the mapping, map just the the fields I want to set a specific analyzer and then use the mongoosastic to go and save a model via my app to set-up the remaining fields that take on the defaults.

**Comment by nozimy** [comment]
`es_analyzer ` is not working. 

I omitted other product fields, here `name` field is considered
```
var productSchema = new Schema({
name: {type: String, es_indexed:true, es_boost:2.0, es_search_analyzer:"my_synonyms", es_analyzer: "my_synonyms"}, 
    description: { type: String,  es_indexed:true}
});
productSchema.plugin(mongoosastic, {
	index: "products_index"
});

let Product = mongoose.model('products', productSchema);

Product.createMapping(
	{
		"analysis" : {
		"filter": {
			"my_synonym_filter": {
				"type": "synonym",
				"synonyms_path": "analysis/synonym.txt"
			}
		},
		"analyzer":{
			"my_synonyms": {
				"tokenizer": "standard",
				"filter": [
					"lowercase",
					"my_synonym_filter"
				]
			}
		}
	}
},
	function(err, mapping){
		if (err){
			console.log(err);
		}
});

exports.Product = Product;

```
