### ISSUE TITLE
Issues with MyModel.synchronize().

### ISSUE THREAD

**Issue by datermine** [mongoosastic/mongoosastic#250]
When I do a simple:

MyModel.synchronize(), I'm getting this error:

```
server-1:  TypeError: this.find(...).batchSize(...).cursor is not a function
server-1:      at Function.synchronize (...node_modules/mongoosastic/lib/mongoosastic.js:492:53)
```

Any thoughts on what might be causing this?

**Comment by remotevision** [comment]
@datermine I get this same problem, any luck working through it?

**Comment by remotevision** [comment]
I was able to fix this just by upgrading to the latest version of `mongoose`

**Comment by isayme** [comment]
`cursor` supported since mongoose@4.5.0, refer https://github.com/Automattic/mongoose/commit/caba5be5c71aa7856cb29f9a3e86f37235183be4
@datermine please check your local mongoose version~

**Comment by datermine** [comment]
Thanks everyone!
