### ISSUE TITLE
Delay on updating with findOneAndUpdate

### ISSUE THREAD

**Issue by enrichz** [mongoosastic/mongoosastic#253]
Hello,
I'm facing a problem when I update a model with findOneAndUpdate and it happens randomly.
I have this piece of code:
```javascript
Model
  .findOneAndUpdate(query, modification, 
      {"new": true, upsert: false, passRawResult: false, 
        "overwrite": false, runValidators: true, 
         setDefaultsOnInsert: true})
  .exec(function(err, result) {
    if(err) {
      // handle error
      return;
    }
    if(!result) {
      // handle error
      return;
    }
    
    result.on('es-indexed', function(err2, data2){
      if (err2) {
        // handle error
        return;
      } else {
        // OK
        return;
      }
    });
  });
```
The code runs without errors and the data is correcly saved in mongodb.
The problem is when immediately after I read the same data from Elasticsearch: it happens randomly that the data are not updated, i.e. I read the old version. After a few seconds (1 or 2) if I read it again, the data is correct.
I'm using mongoosastic 4.0.2 and mongoose 4.5.5
Any ideas?

Thanks

**Comment by isayme** [comment]
@enrichz please see https://github.com/elastic/elasticsearch-js/issues/231

**Comment by SkateFreak** [comment]
i found a olution that worked for me, might help someone...
i switched to ```elasticsearch-js``` library and commented out my ```mongoosastic``` code lines.

you need to add ```refresh: 'true'``` to your ```.create()``` function for it to be available for search after callback (or at least that what i got from reading v5.0 docs), like so:

    elastic
        .create({
            index: elasticIndex,
            type: 'game',
            id: game._id.toString(),
            body: elasticGame,
            refresh: 'true',
        }, (err, res) => {
            if (err) throw err;
            // search here and you'll find it
        });

maybe the plugin lacks this key?

**Comment by guumaster** [comment]
We don't have support for Elastic v5 yet. Right now it has an "eventual consistency" until elastic finish indexing the object

**Comment by enrichz** [comment]
Thanks for your input guys. Any idea about if and when mongoosastic will support the refresh feature?
