### ISSUE TITLE
[nested] nested object under path [xyz] is not of nested type

### ISSUE THREAD

**Issue by florianbuehlmann** [mongoosastic/mongoosastic#276]
Having the following schema:

var SubSchema= new Schema({
  name: { type: String, required: true }
});

var RootSchema = new Schema({
  subs: { type: [SubSchema], es_indexed: true, es_type: "nested", es_include_in_parent: true }
});
RootSchema.plugin(mongoosastic);
var Root= mongoose.model("Root", RootSchema);

and running the following **raw** query:

`Root.esSearch({
"_source" : false,
"query": {
  "nested": {
    "path": "subs",
      "query": {
        "bool": {
          "must": [
            { "match":
              { "subs.name": "somestring" }
            }
          ]
        }
      },
    "inner_hits" : {}
  }
}
}, function(err, results) {
...
});`

throws the error:

org.elasticsearch.transport.RemoteTransportException: [Am_3bKQ][xxx:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: failed to create query: ...
...
Caused by: java.lang.IllegalStateException: [nested] nested object under path [subs] is not of nested type

Even though the schema defines "es_type" with "nested".

Is this a desired behaviour?

**Comment by isayme** [comment]
@florianbuehlmann you should `createMapping` to do init mapping.

**Comment by florianbuehlmann** [comment]
That indeed solved the problem. However in the docs this is nowhere mentioned.
This may have been obvious for ES experts here, but not for novices like me.
Suggest to update docs, keeping this issue open.

**Comment by isayme** [comment]
@florianbuehlmann would you help to add some doc ?

**Comment by florianbuehlmann** [comment]
I am not entirely sure under which circumstances the `createMapping` function is necessary to be called.
For instance looking at the `Setup` title in the README, is it necessary to call `createMapping` even if one would only define `es_indexed: true`?

If so, maybe something among these lines could be put below `In this case only the name field will be indexed for searching.`:

> Everytime elasticsearch specific fields are added or removed the mapping needs to be updated in order to reflect the definitions to elasticsearch.
> This can be done by calling

> `User.createMapping(function(err, mapping) {
>   // mapping now contains the updated elasticsearch mapping
> });`

> (sorry I am not able to format this correctly).

> The function createMapping should be called after defining the schema to ensure the mapping is existing on the elasticsearch instance.

> Refer to the Mapping section below for advanced configuration options.

I am not sure if this is correct regarding the content or not but this is how I interpret looking at https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html and the rest of the README.

**Comment by isayme** [comment]
`In general, the mapping for existing fields cannot be updated.`, so we should createMapping only once.
if the schema changed, most time I prefer to delete the `index/type` and createMapping again.

refer: [Updating field mappings](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/indices-put-mapping.html#updating-field-mappings)
