### ISSUE TITLE
Can't index only the id of a nested object/ref

### ISSUE THREAD

**Issue by ahgentil** [mongoosastic/mongoosastic#277]
````
var User = new Schema({
  name: String
});

var Record = new Schema({
  // ...
  seller: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    es_indexed: true
  }
  // ...
});
````

For this example, when indexing a `Record`, I can only index a `User` object inside it, when actually I just wanted to index the `User`'s id string.

The only way I could achieve that was by modifying the `Record` schema by removing `ref: 'User'`. Only without that I get something like `"seller": "5624fe7467a46bee3537433b"`. 

Am I missing some possible configuration to achieve that without modifying the `Record` schema?

Thanks in advance.

**Comment by isayme** [comment]
I tried your schema, and got this:
![image](https://cloud.githubusercontent.com/assets/1747852/22204588/b7e4d552-e1ad-11e6-9553-9d8ba14bd7f2.png)

**Comment by ahgentil** [comment]
@isayme Humm... Yes. That's the goal. But I can't get to that.

I'm using a recent versions of both `mongoosastic` (4.2.4) and `elasticsearch` (12.1.3) client. But ES is 1.7, so I'm also setting mongoosastic `esClient` myself, and initialising it with `apiVersion: '1.7'`.

This is the error from the `elasticsearch` client:
`````
{
	"error": "MapperParsingException[failed to parse [seller]]; nested: ElasticsearchIllegalArgumentException[unknown property [_id]]; ",
	"status": 400
}
`````

**Comment by isayme** [comment]
you can try delete the exist index and createMapping from latest schema.

**Comment by ahgentil** [comment]
Did you try saving the `record` while having the `seller` populated? The issue happens to me only in that case. If I don't populate it, then it's ok.

Maybe this is not an issue, just how mongoosastic works.

But if it's not possible to achieve what I'm mentioning, then I think it would be a good 'es_' option to have.

**Comment by isayme** [comment]
this is not an issue~
mongoosastic don't know you have populated fields, it just sends current values to ES, and ES failed to parse values since they are not expected~

**Comment by ahgentil** [comment]
Ok, noticed.

To work this out for me I ended up using the `transform`option with something like below, to avoid confirming that all the saves are done with the `seller` not populated.  

``````
  transform: function (data, repo) {
    if (repo.seller && !Types.ObjectId.isValid(repo.seller)) {
      data.seller = repo.seller._id;
    }

    return data;
  }
``````
