### ISSUE TITLE
Populate does not work

### ISSUE THREAD

**Issue by edgarmarkosov** [mongoosastic/mongoosastic#278]
Populate does not work for me as it is written in documentation. It works when provided in hydrateOptions object. 

        model.search(query, {
            hydrate: true,
            hydrateOptions: {
                 populate: [{path: 'path_to_populate'}]
            } 
        }, function (err, res) {});

Please fix this issue in documentation.

**Comment by guumaster** [comment]
Thanks for the heads up, also we are glad to accept your pull request :wink:

**Comment by stephanebressani** [comment]
thanks you, same problem !
