### ISSUE TITLE
geo_point not mapping correctly in nested model

### ISSUE THREAD

**Issue by kahwooi** [mongoosastic/mongoosastic#28]
I have a nested model:

``` javascript
var officeSchema = new Schema({
    _id: Schema.ObjectId,
    name: String,
    location: {
        geo_point: {
            type: String,
            es_type: 'geo_point',
            es_lat_lon: true
        },
        lat: {type: Number},
        lon: {type: Number}
    }
});

var businessSchema = new Schema({
    _id: Schema.ObjectId,
    name: {type:String, es_indexed:true}
    office: {type:[officeSchema], es_indexed:true}
});
```

Indexing:

```
"location": { "lat": 1, "lon": 2}
```

but the office mapping geo_point result is a string:

```
 "office": {
      "properties": {
          "location": {
               "properties": {
                   "lat": {
                        "type": "long"
                     },
                     "lon": {
                        "type": "long"
                     }
                 }
            },
```

Is this a bug?

**Comment by amperesoft** [comment]
Any update on this issue? I am facing the same issue. 

Is it possible to just create our mapping externally and use mongoosastic for initial data load and maintaining indexing on docs?

**Comment by andrewmcwatters** [comment]
:+1: This is blocking development for me. :disappointed:

**Comment by michaek** [comment]
I'm also seeing the same mapping results as the creator of this issue. The elasticsearch documentation seems to describe what the expected mapping of a geo point should be: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-geo-point-type.html

It seems the schema from the original issue would be looking to have a mapping for office like

```
{
    "location" : {
        "type" : "geo_point"
    }
}
```

and the specific format of the location data (string, array, properties) does not need to be reflected in the mapping, as elasticsearch treats it as an input format.

**Comment by amperesoft** [comment]
Guys Sorry for the late reply. I had fixed this issue that time by making changes to mongoosastic library. I am not sure right now what all changes I did but let me know if you are still facing this issue and I will be happy to send you the changed js files of mongoosastic.

Gaurav

**Comment by michaek** [comment]
Thanks, @amperesoft. It would be great to see the changes you made! It sounds like @taterbase is open to a PR.

**Comment by ksavidetove** [comment]
Hello guys I'm facing the exact same issue, as soon as I use references to define my nested models, the resulting mapping become a lat/lon object instead of a geo_point

**Comment by hoangnguyenasnet** [comment]
Hi all, I'm facing the same issue, any update?

**Comment by andrewmcwatters** [comment]
lmao, the last time I dealt with this issue, it had been several companies ago. There isn't a fix for this, afaik. Instead, you'll need to use a different datatype, iirc, as this one is functionally broken.

All the best!

**Comment by andrewmcwatters** [comment]
Oh yes, in addition, this repository is no longer maintained. I'd recommend searching for an alternative solution.

**Comment by hoangnguyenasnet** [comment]
@andrewmcwatters: Thanks for response.

**Comment by edxpertmean1** [comment]
> Guys Sorry for the late reply. I had fixed this issue that time by making changes to mongoosastic library. I am not sure right now what all changes I did but let me know if you are still facing this issue and I will be happy to send you the changed js files of mongoosastic.
> 
> Gaurav

Hi i am facing same issue. Could you please assist me here

**Comment by andrewmcwatters** [comment]
@edxpertmean1 See the comments above.
