### ISSUE TITLE
.synchronize() function throwing this.find(...).batchSize(...).cursor is not a function

### ISSUE THREAD

**Issue by tejpratap46** [mongoosastic/mongoosastic#294]
On line [510](https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L510)

`this.find(query).batchSize(bulk.batch).cursor()` should be `this.find(query).batchSize(bulk.batch).stream()`

Using:
- mongoose: 4.3.4
- mongoosastic: 4.2.4

i did't had time to do tests, so no pull request.

**Comment by isayme** [comment]
you should upgrade your mongoose version 4.5.0+ 
refer: https://github.com/Automattic/mongoose/blob/master/History.md#450--2016-06-13
