### ISSUE TITLE
es_type: 'completion' seems to be ignored

### ISSUE THREAD

**Issue by galkowskit** [mongoosastic/mongoosastic#301]
When I try to create `es_type: 'completion'` on a Mongoose schema property it will get mapped as something else. Trying to use `suggest` later on that field gives:

```
"error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Field [data.nameSearch] is not a completion suggest field"
      }
    ],
```

**Comment by isayme** [comment]
how is your schema definition and how did you search ?

**Comment by galkowskit** [comment]
It's resolved.

Detting: `es_type: 'completion'` on a field in the schema is not enough. To actually have this mapping done I had to add this after plugging in the `mongoosastic` and creating a model.

```
Product.createMapping({}, function(err, mapping) {
    if (err) {
        console.log(err);
    } else {
        synchronizeProducts();
    }
});
```

The `synchronizeProducts()` function is just a wrapper for `synchronize()` method. Only with `createMapping` the `es_type: 'completion'` was taken into account.

**Comment by isayme** [comment]
We need `createMapping` before save a document~

**Comment by qlqllu** [comment]
I would like to add more details about the `createMapping` call:
```
Product.createMapping({
  "mappings" : {
    "product" : { //this is es type name
      "properties" : {
        "name" : { "type" : "completion" }
      }
    }
  }
}, function(err, mapping) {
  if (err) {
    console.error( err);
  } else {
    console.log('ok.');
  }
});
```
