### ISSUE TITLE
search immediately after "es-indexed" returns 0 results

### ISSUE THREAD

**Issue by SkateFreak** [mongoosastic/mongoosastic#304]
newGame.save(err => {
        if (err) throw err;
        newGame.on('es-indexed', (err, res) => {
            Game.search({bool: {must: [{ term: { status: 1 }}]}}, (err, results) => {
                if (err) throw err;
                console.log(results);
            });
        });
    });

the result i get:

```hits: { total: 0, max_score: null, hits: [] } ```

**although ```res``` returns fine**

**Comment by isayme** [comment]
The behavior is known as expected, and we will add document for this.

**Comment by isayme** [comment]
duplicate with #253

**Comment by isayme** [comment]
closed refer #305
