### ISSUE TITLE
17 failing tests on Elastic 5.1.2

### ISSUE THREAD

**Issue by nodkz** [mongoosastic/mongoosastic#307]
Fork repo, try to run tests locally with Elastic 5.1.2 and got 17 failing tests.

@isayme @guumaster any plans for update tests, travis (currently runs tests on Elastic Search 1.4.0) to the latest version of Elastic server?

I'm at a loss - rewrite mongoosastic from scratch or keep going with you... For now for me too many barriers for improving this lib: code-style, ES6, backward compatibility, too slow tests. Also I have some gaps how elastic driver works. All together brings me to write absolutely new module from scratch.

How do you see future of `mongoosastic`?

**Comment by nodkz** [comment]
Found another lib [mongoose-elasticsearch-xp](https://github.com/jbdemonte/mongoose-elasticsearch-xp):
- has Promises
- supports Elastic 5

Try to play with it.

**Comment by guumaster** [comment]
All tests passing on master. Version 4.5.0 support ES 6.x.
