### ISSUE TITLE
Indexing On Demand crashes when no callback is presented.

### ISSUE THREAD

**Issue by jonathan-nielsen** [mongoosastic/mongoosastic#317]
I have a function where I index a document when a function is called and not created, therefore i want to use the Index On Demand functionality. I do not wish to have a callback and when no callback is presented to doc.index() it crashes with `Cannot read property 'index' of undefined`. 

When i pass function like `doc.index(() => {})` it works.

Example when it's not working:
```
async function publish(req) {
    let doc = await model.findById(req.params.id);

    doc.published = true;

    doc.index(); // Throws the error "Cannot read property 'index' of undefined" here.

    doc = await doc.save();

    return doc;
}
```

Example when it's working:
```
async function publish(req) {
    let doc = await model.findById(req.params.id);

    doc.published = true;

    doc.index(() => {});

    doc = await doc.save();

    return doc;
}
```

I first thought "doc" was undefined since it said **index** of **undefined**. But it seems to be the source code of the package that is crashing when it's trying to reach a key called index from an undefined object.

**Comment by isayme** [comment]
please show us your node version, mongoose version, mongoosastic version.

and show your error stack.
