### ISSUE TITLE
Fielddata is disabled on text fields by default

### ISSUE THREAD

**Issue by aryeharmon** [mongoosastic/mongoosastic#324]
Fielddata is disabled on text fields by default. Set fielddata=true on [*****] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."

Is there any way to add a Fielddata = true, to a specific field?

**Comment by Jaikant** [comment]
I too need to set fielddata to true, is there a way to do that?

**Comment by aryeharmon** [comment]
yes. very simple,
`es_fielddata: true`

**Comment by simo385** [comment]
Hello,
for me "es_fielddata: true" in my model doesn't work.

I need to use the API: PUT my_index/_mapping {...} to set fielddata.

**Comment by dhianpratama** [comment]
Hi, is there any solution for this?

**Comment by aryeharmon** [comment]
@simo385 that's because you need to update the model, delete elastic search index add es_fielddata = true, and re-sync the data.

**Comment by simo385** [comment]
Dear @aryeharmon, I already deleted the index and did re-sync, but it doesn't work.

**Comment by simo385** [comment]
any updates for es_fielddata field?

**Comment by oxyii** [comment]
@simo385 So strange but `es_fielddata` (and others `es_*`) works **ONLY** if type present because of this
https://github.com/mongoosastic/mongoosastic/blob/1ba9fc864fc61d973021e51a3baeafcee93427e6/lib/mapping-generator.js#L96-L99

So 
```js
fieldName: {
  type: String,
  es_type: 'string',
  es_fielddata: true,
},
```
will works
