### ISSUE TITLE
_doc.index is not a function

### ISSUE THREAD

**Issue by aabanaag** [mongoosastic/mongoosastic#339]
## Your Environments
- mongoosastic version: 4.3.0
- node version: 6.2.2
- mongoose version: 4.5.3
- elasticsearch version: 5.3.0

## Expected Behavior
It should update the model

## Actual Behavior
Having error(s) when trying to update the model. I'm using `Model.findOneAndUpdate` with `new:true` which was specified in the readme file.

## Error Stack
![image](https://cloud.githubusercontent.com/assets/2245822/24801508/1ffee99e-1bd7-11e7-8460-0e8ee421dd14.png)

**Comment by aabanaag** [comment]
![image](https://cloud.githubusercontent.com/assets/2245822/24802635/34bda376-1bdb-11e7-9d3d-c61135307f80.png)
This was my code. I mistakenly added .lean(true) which caused the error.

**Comment by superbarne** [comment]
Hi can i get this to work with lean:true?

**Comment by BhupenPal** [comment]
> Hi can I get this to work with lean: true?

Hey @superbarne,
This doesn't work with lean: true, lean basically returns a POJO (Plain Old JavaScript Object) and it is not a MongoDB document, hence no MongoDB operations can be performed upon it.

Thanks

**Comment by Zakharen** [comment]
@superbarne @aabanaag try to use `Wallet.updateOne` instead of 'Wallet.findOneAndUpdate'
