### ISSUE TITLE
Index was not created upon start

### ISSUE THREAD

**Issue by aabanaag** [mongoosastic/mongoosastic#342]
## Your Environments
- mongoosastic version: 4.3.0
- node version: 6.2.2
- mongoose version: 4.5.3
- elasticsearch version: 5.1.1

## Expected Behavior
Should sync old data upon starting api.

## Actual Behavior
Index was not created upon start of API.

code below:
```
model.plugin mongoosastic,
  index: wa_model
  hydrate: true
  hydrateOptions:
     lean: true
  hosts: [url]
```
But when I added this
```
model.createMapping (err, mapping) ->
  if err
    console.log 'error creating mapping (you can safely ignore this)'
    console.log err
  else
    console.log 'mapping created!'
    console.log mapping
  return
```
Index was created but data was not existing.

## Error Stack
no error.

**Comment by isayme** [comment]
[Creating the mapping is a one time operation and should be called manually.](https://github.com/mongoosastic/mongoosastic#creating-mappings-on-demand)
