### ISSUE TITLE
Mongoosastic Stores only es_indexed:true fields in ES

### ISSUE THREAD

**Issue by Mastermaulik** [mongoosastic/mongoosastic#355]
## Your Environments
- mongoosastic version:4.3.0
- node version: node 7
- mongoose version: 4.8.4
- elasticsearch version: 5.4

## Expected Behavior

I have created my schema as follows:
```
_id: {
        type: Schema.Types.ObjectId,
        es_indexed: true
      },
      name: String,
      email: String,
      managerEmails: [String],
      groupNames: [String],
      enrolledToGroupName: String,
      isAddedToGroup: String,
      companyId: {
        type: Schema.Types.ObjectId,
        required: true,
        es_indexed: true
      }
```
I have added mongoosastic as follows:
```
schema.plugin(mongoosastic, {
  index: 'contentsession',
  type: 'expandedEvent',
  esClient: getElasticConnection(),
  saveOnSynchronize: false // triggers Mongoose save (and pre-save) method when synchronizing a collection/index
});
```

Now the only fields that are stored are the ones which are having es_indexed:true.

I want to have the same document that is stored in mongodb to be stored in ES as well.

Is there a way to do so?

**Comment by isayme** [comment]
remove `es_indexed: true` will work for you.

**Comment by Mastermaulik** [comment]
@isayme, I found that this thing works. I come from mongodb background where storing and indexing means different things. Thanks for the response.

**Comment by Sabya1981** [comment]
removing es_indexed: true indexes Everything !!! That's not what I want any remedy
