### ISSUE TITLE
search returning results from wrong index

### ISSUE THREAD

**Issue by Torwori** [mongoosastic/mongoosastic#36]
Hi, I need some help.
I have a model defined like this: 

    var productSchema = new Schema({'master': Array, ...})
    productSchema.plugin(mongoosastic);
    var Product = mongoose.model('Product', productSchema);

Using the following query, I get results that aren't from the products index:

    Product.search({
      'match': {
        'master' : 'somestring' // there are multiple schemas which contain 'master': Array
      }
    }, function (err, products) {
          console.log(products.hits.hits)
    });

    // the output contains hits that have '_index' different than 'products'

What am I doing wrong?

I've hacked around the issue by using a filtered query where the filter checks for a field that only exists for products, but I'm convinced that it's redundant and that I did something wrong in my code.

**Comment by guumaster** [comment]
I'm trying to reproduce this situation but I can't. I've made this simple [gist](https://gist.github.com/guumaster/4ca7abbf63716861a245) but it works as expected. 

Could you add more info on your schemas and their relations?

**Comment by Torwori** [comment]
It looks like I made a mistake when submitting the issue, one schema had a `'master': Array` , while the other had `'master': String`. Sorry about that.
