### ISSUE TITLE
esTruncate delete only the first 10 items

### ISSUE THREAD

**Issue by lioramrosi** [mongoosastic/mongoosastic#366]
Hi,
I'm trying to use esTruncate method and it seems not works well.
When I call the method only the first 10 items delete.
Thanks

## My Environments
- mongoosastic version: 4.3.0
- node version: 6.0
- mongoose version: 4.5.0
- elasticsearch version: 2.3.1

**Comment by ksmithut** [comment]
In the method, it looks like it just does an esSearch call and unindexes the resulting hits, but only those returned in that "page". https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L439
