### ISSUE TITLE
Update index issue when save-update model in mongoosastic

### ISSUE THREAD

**Issue by bhutiyaDilip** [mongoosastic/mongoosastic#367]
## Your Environments
-mongoosastic version: 5.4.0
-node version: 1.6.0
-mongoose version: 4.8.5
-elasticsearch version: 2.3.1

## Expected Behavior
When i update mydocument then index is not refresh or update in mongoosastic.
Please Help me out--

## Error Stack
Model like...

var mongoose = require('mongoose')
, mongoosastic = require('mongoosastic')
, Schema       = mongoose.Schema;

// set up a mongoose model
var PersonalSchema=new Schema({
	parent_id: { type: Schema.Types.ObjectId, ref: 'Profile'},
	title: String,
	academic_title: {type:String, es_indexed:true},
	academic_degree: String,
	name:{type:String, es_indexed:true},
	citizen: {type:String, es_indexed:true},
	dob: {type:String, es_indexed:true}
})
PersonalSchema.plugin(mongoosastic);
var Personal = mongoose.model('Personal', PersonalSchema)
, stream = Personal.synchronize()
, count = 0;
stream.on('data', function(err, doc){
	count++;
});
stream.on('close', function(){
	console.log('Personal indexed ' + count + ' documents!');
});
stream.on('error', function(err){
	console.log(err);
});
module.exports = Personal;

Update Code like...
Personal.findOneAndUpdate({'parent_id':req.body._id},req.body.personal,{upsert:false}, function(err, doc){
		    if (err) throw err;
		    if(doc){
		    	doc.on('es-indexed', function(err, res){
				    if (err) throw err;
			});
   		     logger.info("personal successfully updated");
		    }
});

**Comment by ietuday** [comment]
@bhutiyaDilip I got the same issue 
-mongoosastic version: 4.4.1
-node version: 10.16.2
-mongoose version: 5.4.6
-elasticsearch version: 6.5

Please help if you got any solutions. Thanks in advance.
