### ISSUE TITLE
Supported Mongoose and Elasticsearch version?

### ISSUE THREAD

**Issue by shenkev** [mongoosastic/mongoosastic#369]
I looked around but couldn't find this information stated explicitly anywhere. From the change log, mongoosastic currently supports up to Mongooses 4.8.4 and Elasticsearch 2?

But checking package.json it seems like Mongoose 4.10 and Elasticsearch 13.0.1 is supported? 

Is Elasticsearch 13.0.1 equivalent to the api version of Elasticsearch 5? It seems like multi_field has be removed for ES5, and the recommended solution is to specify "fields" param instead.  Is this supported in Mongoosastic right now? Relevant link: https://stackoverflow.com/questions/40301061/elasticsearch-5-mapperparserexception-with-multi-field

**Comment by markusv** [comment]
Did you find a solution for this?
