### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jemliF** [mongoosastic/mongoosastic#380]
## Environments
- mongoosastic version: ^4.2.4
- node version: 7.7.1
- mongoose version: 3.4.2
- elasticsearch version: 5.0.0

## Expected Behavior
I have an architecture of nested documents:
**Quiz: an array of questions**
```
let QuizSchema = new Schema({
    questions: {
        type: [Question],
        es_indexed: true,
        es_type: "nested",
        es_include_in_parent: true,
        required: false
    }
})
```
**Question: an array of proposition**
```
let QuestionSchema = new Schema({
    propositions: {
        type: [Proposition],
        es_indexed: true,
        es_type: "nested",
        es_include_in_parent: true,
        required: false
    }
})
```
**Proposition**
```
let PropositionSchema = new Schema({
    content: {
        type: String,
        es_indexed: true,
        es_index: 'analyzed',
        es_type: 'string'
    },
    favorable: {
        type: Boolean,
        required: false,
        es_type: 'boolean',
        es_indexed: true
    }
})
```
## Actual Behavior

When I try to save a **Quiz** using this data: 
```
{  
   "content":"nodejs",
   "trainer":"58b7de06adb29d2ed7185065",
   "questions":[  
      {  
         "content":"what is node js",
         "propositions":[  
            {  
               "content":"language",
               "favorable":false
            },
            {  
               "content":"framework",
               "favorable":true
            }
         ]
      }
   ]
}
```
Data is saved in MongoDB, but not indexed in Elasticsearch and the app crashes 
## Error Stack
I get this error:

> /src/app/node_modules/mongodb/lib/utils.js:123
>      process.nextTick(function() { throw err; });
>                                    ^
>  TypeError: Cannot read property 'toLowerCase' of undefined
>      at setIndexNameIfUnset (/src/app/node_modules/mongoosastic/lib/mongoosastic.js:230:28)
>      at EmbeddedDocument.schemaIndex [as index] (/src/app/node_modules/mongoosastic/lib/mongoosastic.js:371:5)
>      at EmbeddedDocument.postSave (/src/app/node_modules/mongoosastic/lib/mongoosastic.js:260:14)
>      at Function.<anonymous> (/src/app/node_modules/mongoose/lib/schema.js:1153:17)
>      at emitOne (events.js:96:13)
>      at Function.emit (events.js:191:7)
>      at EventEmitter.<anonymous> (/src/app/node_modules/mongoose/lib/types/embedded.js:39:23)
>      at emitOne (events.js:96:13)
>      at EventEmitter.emit (events.js:191:7)
>      at EmbeddedDocument.Document.(anonymous function) [as emit] (/src/app/node_modules/mongoose/lib/document.js:98:44)
>      at EventEmitter.notify (/src/app/node_modules/mongoose/lib/types/documentarray.js:275:18)
>      at emitOne (events.js:101:20)
>      at EventEmitter.emit (events.js:191:7)
>      at EmbeddedDocument.Document.(anonymous function) [as emit] (/src/app/node_modules/mongoose/lib/document.js:98:44)
>      at EventEmitter.notify (/src/app/node_modules/mongoose/lib/types/documentarray.js:275:18)
>      at emitTwo (events.js:111:20)

**Comment by Morphexe** [comment]
@jemliF I am getting the exact same issue, did you manage to fix it?

**Comment by w0bbes** [comment]
Having the exact same issue when trying to add a new entry to mongodb through mongoose:
mongoosastic: 4.4.1
mongoose: 4.13.11
Elasticsearch: 6.23

**Comment by scarabetta** [comment]
2021: Suddenly I started getting that same error message. As the document was saved in MongoDB, I suspect it's something with mongoosastic / elasticsearch. In fact, if I remove the plugin, the error dissapears.

I see many people came across this issue, but so far haven't found a workaround. I really would like to put back mongoosastic!

**Comment by RacketyWater7** [comment]
I think may be it has to do something with the naming of the models in mongoose. I just feel like it but not 100% sure. So do make sure you're naming it according to mongo customs ""

**Comment by NamiMandaliya** [comment]
It was the issue with collection name for me in schema file (product.js)
_Product = module.exports = mongoose.model(products, ProductSchema)_
