### ISSUE TITLE
Indexing Mongoose References as Nested Object

### ISSUE THREAD

**Issue by speedingdeer** [mongoosastic/mongoosastic#386]
When I index references like here it works great

objects: [{
    type: Mongose.Schema.Types.ObjectId, ref: 'Object',
    es_schema: Object, es_indexed: true,
 }],

When I try to add es_type: 'nested', can't create a mapping. Is there any way I can index references as nested objects?

**Comment by jemliF** [comment]
This works for me:
```
let ChapterSchema = new Schema({
    name: {
        type: String,
        required: false,
        es_type: 'multi_field',
        es_indexed: true
    },
    lessons: {type: [Lesson], es_indexed: true, es_type: "nested", es_include_in_parent: true}
})
let CourseSchema = new Schema({
chapters: {type: [ChapterSchema], es_indexed: true, es_type: "nested", es_include_in_parent: true, required: false}
})
```

**Comment by speedingdeer** [comment]
You are indexing and object (ChapterSchema) not the reference (ObjectId) it's a different thing

**Comment by johnguerson** [comment]
I'm wondering the same thing here, is that possible in mongoosastic? 
I don't wanna make my document a sub-document just so I can map it to a ES nested object, I would have to change a lot in my  applicaton just to cope with that change. Just anybody have a thought on this?
