### ISSUE TITLE
TypeError: Undefined type at `_id.auto`

### ISSUE THREAD

**Issue by jondavidjohn** [mongoosastic/mongoosastic#39]
Upon upgrading from `0.0.11` -> `0.5.0` our schema definitions started throwing this error..

```
/Users/.../node_modules/mongoose/lib/schema.js:362
    throw new TypeError('Undefined type at `' + path +
          ^
TypeError: Undefined type at `_id.auto`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/.../node_modules/mongoose/lib/schema.js:362:11)
    at Schema.path (/Users/.../node_modules/mongoose/lib/schema.js:305:29)
    at Schema.add (/Users/.../node_modules/mongoose/lib/schema.js:217:12)
    at Schema.add (/Users/.../node_modules/mongoose/lib/schema.js:212:14)
    at new Schema (/Users/.../node_modules/mongoose/lib/schema.js:79:10)
    at Object.<anonymous> (/Users/.../models/logs/segment.js:7:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Here is the schema definition

```javascript
var SegmentSchema = new Schema({
  name: String,
  date: { type: Date, default: Date.now },
  likelyhood: Number,
  pathId: Schema.Types.ObjectId,
}, {
  db: 'logs'
});
```

Again, this doesn't have an issue under `0.0.11`, but does once upgraded to `0.5.0`.

The end goal would be to catch up completely (and the same error presents itself under `2.0.6`).

**Comment by leobartkus** [comment]
Do you have multiple schemas in your project?  In my project, mongoosastic was adding a type field to the ObjectId class, causing mongoose to get confused and blow up on the second schema to get registered.

**Comment by guumaster** [comment]
Could you try versión 2.0.8? We've added a patch for a similar error.

**Comment by jedverity** [comment]
I have the same problem with mongoose 4.1.12 and mongoosastic 3.3.2

**Comment by jedverity** [comment]
If it helps anyone else, it appears that this happens when you have an ObjectId field definition with nothing but the type:
```
myField: Schema.Types.ObjectId
```
Changing the definition to an object fixes it:
```
myField: { type: Schema.Types.ObjectId }
```

**Comment by patrickd-** [comment]
> Changing the definition to an object fixes it:

I can confirm this.

Seems like a bug to me.

**Comment by robertleeplummerjr** [comment]
We are still seeing this issue, even though we are on latest.  I did try @glortho's fix, but to no avail.  Any thoughts?

**Comment by robertleeplummerjr** [comment]
Trying your fix @boblauer.

**Comment by robertleeplummerjr** [comment]
:+1: from me, works like a charm!

_crowd starts saying: merge it... merge it... merge it!_
