### ISSUE TITLE
Searching for nested models

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#4]
https://github.com/jamescarr/mongoosastic/issues/67#issue-16566224

> I would like to be able to search for nested models. For example, in this schema:
> 
> ``` javascript
> var Comment = new Schema({
>     title: String
>   , body: String
>   , author: String
> })
> 
> 
> var User = new Schema({
>     name: {type:String, es_indexed:true}
>   , email: String
>   , city: String
>   , comments: {type:[Comment], es_indexed:true}
> })
> ```
> 
> I would like to search for comments that match a certain text, for users in a certain city. I would like the query to return only the comments that match the query.
> 
> My questions are:
> 1. Is there a way to store the comments in a separate index, where the user is the parent? (while still using mongoosastic and not a custom solution)
> 2. Is there another way to search for the comments, without the need to filter the results after they are returned?

**Comment by isayme** [comment]
the feature already added, see document [Indexing Nested Models](https://github.com/mongoosastic/mongoosastic#indexing-nested-models)
