### ISSUE TITLE
Mongoosastic Limit Synchronize for Only 20 Documents

### ISSUE THREAD

**Issue by sitompul** [mongoosastic/mongoosastic#404]
I have 34 documents. During truncate, i called synchronize method. But it only managed indexing 20 Documents. The other 14 documents still left un-indexed

## Your Environments
- mongoosastic version: 4.3.0
- node version: 8.5.0
- mongoose version: 4.6.6
- elasticsearch version: 5.6.2

## Expected Behavior
Indexing more that 20 Documents

## Actual Behavior
indexing only happened for 20 Documents, i have 14 left

## Error Stack
No Error

**Comment by gate3** [comment]
This is the current behaviour for me too. Mine indexes only 10 out of 401
