### ISSUE TITLE
How to query multiple indexes or multiple data collection under?

### ISSUE THREAD

**Issue by janryWang** [mongoosastic/mongoosastic#41]
Because I need a global query plan

**Comment by ishakya** [comment]
I tried something like this and it worked for me. Here is the part of the code:
var collection = ['assets','users'];
var types = ['asset', 'user'];
	asset.search({query_string: {query: data}}, {index: collection, type: types}, function(err, results){
	if(err){
			return callback(err);
		}
	callback(null, results);
	})

**Comment by guumaster** [comment]
The plugin fix one index on each model, so you can't do that with this plugin, but you can do it with an Elasticsearch client as @ishakya shared.

**Comment by PARAGJYOTI** [comment]
It really helped.. works fine

**Comment by tgalkowski7ninjas** [comment]
Any idea how to return mongoose documents using this approac? Something like `{ hydrate: true }`?

**Comment by BigFax** [comment]
We should query them manually by ids. (in case someone else would like to know)
