### ISSUE TITLE
Please update package.json to support the newest version of elasticsearch package (v 14.1.0)

### ISSUE THREAD

**Issue by msevera** [mongoosastic/mongoosastic#419]
## Your Environments
- mongoosastic version: 4.3.0
- node version: 8.9.4
- mongoose version: 5.0.3
- elasticsearch version: 6.1.3

## Expected Behavior

Current version of mongoosastic has reference to elasticsearch package of version 12.1.3. But there is the newest one 14.1.0 which supports ElasticSearch 6. 
So some features like bulk indexing are broken for now (if to use ElasticSearch 6)

**Comment by ngoctranfire** [comment]
Not sure, but what is the status of this at the moment?

**Comment by msevera** [comment]
Mongoosastic uses elasticsearch package version 13.3.0 after recent update. For this js version the default is Elasticsearch API 5.5. So, there could be still issues if to install ElasticSearch 6.2

**Comment by msevera** [comment]
We've updated our system to ElasticSearch 6.2.2 and everything is working ok now.

**Comment by zphingphong** [comment]
ES6 isn't quite working. Generated mapping for String and ID is still `string`, which is replaced in ES6 by `text`.

**Comment by guumaster** [comment]
new version have all the deps updated.
