### ISSUE TITLE
Referencing to another index in elasticsearch

### ISSUE THREAD

**Issue by janryWang** [mongoosastic/mongoosastic#42]
I am using Elasticsearch for searching the indexed documents. The documents are indexed using mongoosastic. How could i refer to another index in a query like populate in mongoose or join in SQL. Please help me with an example.

i am having two index namely project and user. In project collection of mongodb, refers to user collection of mongodb. I am searching on project using elasticsearch and getting the results. But i want to refer user index in elasticsearch in same query fired on project index. So how could i refer user index from project index.

**Comment by taterbase** [comment]
Hey @janryWang, I know this is possible but not sure exactly how. I don't really use this project much anymore and have fallen out of understanding all of the intricacies. If you need to you can use the native driver by accessing the static value `esClient` (https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L28)

```javascript
MyModel.esClient.search(/ *** /)
```

You can find the api for the Elasticsearch driver here: http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/api-reference.html

**Comment by janryWang** [comment]
@taterbase I give this project a PR,but CI always faild! why?

**Comment by guumaster** [comment]
I think using more than one index in a Mongoose model is beyond this plugin. You should use directly an Elasticsearch client to do that.
