### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined when adding record

### ISSUE THREAD

**Issue by w0bbes** [mongoosastic/mongoosastic#441]
Trying to add a new record crashes the server.

Model/schema:

const Schema = mongoose.Schema

const tradeSchema = mongoose.Schema({
  addedFromMarket: {
    type: [itemSchema],
    es_indexed: true
  },
  addedFromInventory: {
    type: [itemSchema],
    es_indexed: true
  },
  comments: Schema.Types.Mixed,
  timestamp: String,
  userInfo: Schema.Types.Mixed,
  description: {
    type: String,
    es_indexed: true
  },
  likes: Array,
  tradeLink: String,
  lastModified: {
    type: Date,
    default: Date.now
  }
})

tradeSchema.plugin(mongoosastic, {
  hosts: [
    'ip:9200'
  ]
})

const TradeModel = mongoose.model('Trades', tradeSchema)

## Your Environments
- mongoosastic version: 4.4.1
- node version: 8.9.4
- mongoose version: 4.13.11
- elasticsearch version: 6.2.3

## Expected Behavior
Im adding a new record with mongoose with mongoosastic hooked up

## Actual Behavior
It's adding the record, but crashes the server.

## Error Stack
Server logs:
0|server   |     TypeError: Cannot read property 'toLowerCase' of undefined
0|server   |     at setIndexNameIfUnset (/skintraderz/webclient/node_modules/mongoosastic/lib/mongoosastic.js:231:29)
0|server   |     at EmbeddedDocument.schemaIndex [as index] (/skintraderz/webclient/node_modules/mongoosastic/lib/mongoosastic.js:372:5)
0|server   |     at EmbeddedDocument.postSave (/skintraderz/webclient/node_modules/mongoosastic/lib/mongoosastic.js:261:14)
0|server   |     at Function.<anonymous> (/skintraderz/webclient/node_modules/mongoose/lib/schema.js:1181:17)
0|server   |     at emitOne (events.js:121:20)
0|server   |     at Function.emit (events.js:211:7)
0|server   |     at EventEmitter.<anonymous> (/skintraderz/webclient/node_modules/mongoose/lib/types/embedded.js:39:23)
0|server   |     at emitOne (events.js:116:13)
0|server   |     at EventEmitter.emit (events.js:211:7)
0|server   |     at EmbeddedDocument.Document.(anonymous function) [as emit] (/skintraderz/webclient/node_modules/mongoose/lib/document.js:112:44)
0|server   |     at EventEmitter.notify (/skintraderz/webclient/node_modules/mongoose/lib/types/documentarray.js:275:18)
0|server   |     at emitTwo (events.js:131:20)
0|server   |     at EventEmitter.emit (events.js:214:7)
0|server   |     at model.Document.(anonymous function) [as emit] (/skintraderz/webclient/node_modules/mongoose/lib/document.js:112:44)
0|server   |     at /skintraderz/webclient/node_modules/mongoose/lib/model.js:275:11
0|server   |     at /skintraderz/webclient/node_modules/mongoose/lib/model.js:164:7

**Comment by msilesgap** [comment]
I'm getting the same issue, is there a fix for this?

**Comment by sajadghawami** [comment]
same here

**Comment by Abel5173** [comment]
If anyone has gotten the answer, please
