### ISSUE TITLE
Issue in connecting cloud url

### ISSUE THREAD

**Issue by mrsafi** [mongoosastic/mongoosastic#45]
thanks for good lib

 i am trying connect  by clould url (https://{key_name}:{key}@fili-us-east-1.searchly.com). while creating mapping i am getting follwing error:
**Elasticsearch WARNING: 2015-02-24T07:30:22Z**
  **Unable to revive connection: http://{key_name}:{key}@fili-us-east-1.searchly.com:9000/**

**Elasticsearch WARNING: 2015-02-24T07:30:22Z**
  No living connections

Below is my code

var url = new URL('https://site:{key_name}:{key}@fili-us-east-1.searchly.com');
console.log(url);
bookSchema.plugin(mongoosastic,{
  host:url.host,
  port: url.port,
  
  auth: url.auth
//  ,curlDebug: true
});

var Book = mongoose.model("Book", bookSchema);

Book.createMapping(function(err, mapping){
  if(err){
    console.log('error creating mapping (you can safely ignore this)');
    console.log(err);
  }else{
    console.log('mapping created!');
    console.log(mapping);
  }
});

**Comment by guumaster** [comment]
It seems a connection problem, is the connection string OK? Do you have access from the command line try to curl your ES from the same machine that node is running and check the connection.
