### ISSUE TITLE
Change Travis-CI to use docker images provided by Elastic

### ISSUE THREAD

**Issue by guumaster** [mongoosastic/mongoosastic#453]
In the current build we are using `elasticsearch` provided by TravisCI. Maybe we have better control if we change the pipeline to use docker images pulled directly from `docker.elastic.co/elasticsearch/elasticsearch` repo.

**Comment by sachincool** [comment]
I would like to work on it. :1st_place_medal:

**Comment by guumaster** [comment]
Cool @sachincool You can try to run it locally instead of going only in Travis-CI. I'd be lot faster and easier to debug. If you get the test working locally then we can see why is getting stuck on the CI. 
Try running only the tests and no other task like `coveralls` or `lint`

**Comment by sachincool** [comment]
@guumaster  Yes that helped, I was running it live, I added the `-d` to make it as a daemon. and fixed the eslint tests as well with `--fix` 
after this other tests are passing but the coverage tests have some problem. 
elasticsearch can be verified by `curl http://127.0.0.1:9200/_cat/health` resulting an 100% green light
do you know why this is occuring? [here](https://travis-ci.org/sachincool/mongoosastic/jobs/441252882)
``` 
=============================================================================
Writing coverage object [/home/travis/build/sachincool/mongoosastic/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/sachincool/mongoosastic/coverage]
=============================================================================
=============================== Coverage summary ===============================
Statements   : 92.19% ( 496/538 )
Branches     : 85.25% ( 364/427 )
Functions    : 97.37% ( 37/38 )
Lines        : 92.28% ( 490/531 )
================================================================================
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.```

**Comment by guumaster** [comment]
Good work. Tests are failing on the master branch. So it's ok, now we need to update code and fix the tests

Can you branch from develop branch and make the PR there?
