### ISSUE TITLE
Cannot find a way to paginate results

### ISSUE THREAD

**Issue by Torone** [mongoosastic/mongoosastic#46]
I think the documentation lack of something...
I'm trying to follow the original ElasticSearch properties to insert `size` and `from` but without success...

Actually I'm trying to perform a full text search on my users and the controller receive as body the entire string:

```
User.search({
    query_string: {
      query: req.body.search
    }
},
{ hydrate: true },
function(err, results) {
    users: results.hits.hits
});
```

Where should I define `from` and `size` to handle a pagination?

**Comment by Torone** [comment]
It seems like the param `query` is repeated twice if I do:

```
User.search({
    query: {query_string: {query: req.body.q}}
    ...
```

Error:

```
Error: SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[AwiY7iqIQV-rvWT1TtlrPg][users][0]: SearchParseException[[users][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query":{"query_string":{"query":"something"}}}}]]];
```

**Comment by jitowix** [comment]
I think you should do that:
```
User.search({
    query_string: {
      query: req.body.search
    }
}, { 
  hydrate: true,
  size: 10,
  from: 2 
}, function(err, results) {
    users: results.hits.hits
});
```

**Comment by taterbase** [comment]
Thank you @jitowix, you are correct. Options are passed in after the query object.

https://github.com/mongoosastic/mongoosastic#queries
