### ISSUE TITLE
 [mapper_parsing_exception] No handler for type [string] declared on field

### ISSUE THREAD

**Issue by ietuday** [mongoosastic/mongoosastic#462]
[mapper_parsing_exception] No handler for type [string] declared on field

## Your Environments
- mongoosastic version: 4.4.1
- node version: 10.11.0
- mongoose version: 4.3.4
- elasticsearch version: 6.5.1

## Expected Behavior
Create Map between Mongo and Elastic replica Set.
## Actual Behavior
It's giving an error in createMapping method.
"[mapper_parsing_exception] No handler for type [string] declared on field [category]"
## Error Stack
On Product Schema : 
var mongoose = require('mongoose');
var mongoosastic = require('mongoosastic');
var Schema = mongoose.Schema;

var ProductSchema = new Schema({
    category: { type: Schema.Types.ObjectId, ref: 'Category'},
    name: String,
    price: Number,
    image: String
});

ProductSchema.plugin(mongoosastic, {
    hosts: [
        'localhost:9200'
    ],
});

module.exports =  mongoose.model('Product', ProductSchema);

CreateMapping Method: 
Product.createMapping(function(err, mapping) {
    if (err) {
      console.log("error creating mapping");
      console.log(err);
    } else {
      console.log("Mapping created");
      console.log(mapping);
    }
  });
**************************************************************************************************************
  status: 400,
  displayName: 'BadRequest',
  message:
   '[mapper_parsing_exception] No handler for type [string] declared on field [category]',
  path: '/products/_mapping/product',
  query: {},
  body:
   '{"product":{"properties":{"category":{"type":"string"},"name":{"type":"string"},"price":{"type":"double"},"image":{"type":"string"}}}}',
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category]"}],"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
**************************************************************************************************************
THanks in advance

**Comment by IniterWorker** [comment]
Hello @ietuday,

It's about the fact the new version of elasticsearch doesn't use the string as a handler.

Look up at [https://www.elastic.co/blog/strings-are-dead-long-live-strings](https://www.elastic.co/blog/strings-are-dead-long-live-strings).

**Comment by jahirfiquitiva** [comment]
is there a workaround or a way to fix this without relying on mongoosastic updates?
