### ISSUE TITLE
completion suggester not working 

### ISSUE THREAD

**Issue by Craques** [mongoosastic/mongoosastic#466]
## Your Environments
- mongoosastic version: 4.4.1
- node version: 8.9.4
- mongoose version: 5.0.10
- elasticsearch version: 6.2.4

## Expected Behavior

I am trying to implement simple autocompletion in my app, I have searched around and arrived at [this answer on Stackoverflow](https://stackoverflow.com/questions/32461260/use-mongoosastic-for-an-autocomplete), maybe it is outdated but it is not working as expected

## Actual Behavior
I am getting an error which suggests I change to suggest_field, afterwards I get an error which seems simple but I cannot comprehend

## Error Stack

**Error 1**

"msg": "[illegal_argument_exception] request [/products/product/_search] contains unrecognized parameter: [suggest] -> did you mean [suggest_field]?",
    "path": "/products/product/_search",
    "query": {
        "suggest": {
            "product-suggest": {
                "text": "oneplus",
                "completion": {
                    "field": "productName"
                }
            }
        },
        "size": 0
    },

**Error 2 after switching to suggest_field**

`msg": "[illegal_argument_exception] suggestion field name is empty",
    "path": "/products/product/_search",
    "query": {
        "suggest_field": {
            "product-suggest": {
                "text": "oneplus",
                "completion": {
                    "field": "productName"
                }
            }
        },
        "size": 0
    },
    "body": "{}",
    "statusCode": 400,
    "response": "{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"suggestion field name is empty\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"suggestion field name is empty\"},\"status\":400}"`

**Comment by markusv** [comment]
Hi, did you get this to work? I have the same problem
