### ISSUE TITLE
node engine check in package.json is not strict, able to install with node 6

### ISSUE THREAD

**Issue by curioustushar** [mongoosastic/mongoosastic#481]
## Your Environments
- mongoosastic version: 4.5.0
- node version: 6.14.4
- mongoose version: 5.6.0
- elasticsearch version: 5.6.16

## Expected Behavior

on `npm install`, it should throw a warning - `Unsupported engine for mongoosastic@4.5.0: wanted: {"node":">= 8.0"} (current: {"node":"6.14.4","npm":"6.9.0"})`.

## Actual Behavior

Installation works fine when installed from npm with node 6.

![image](https://user-images.githubusercontent.com/12570521/59558649-75b43200-9014-11e9-97cc-42c9190ab7e4.png)

Installation works but with some warnings on the master branch with node 6.

![image](https://user-images.githubusercontent.com/12570521/59558631-1eae5d00-9014-11e9-90d0-9679cd521f1d.png)

**Comment by curioustushar** [comment]
User can set `npm config set engine-strict true` to enable the strict validation check.

**Comment by guumaster** [comment]
Actually it will probably work fine. Version `>= 8` is more a recommendation due to the fact that we only run automated ci tests on Node 8 and the stable branch.

Do you know of something that brake on older versions?

**Comment by curioustushar** [comment]
@guumaster As of now, I guess nothing breaks. But as we look forward to enhancing the product, we will be writing the code as per the latest ES syntax, which will break in node 6x eg. async await, etc.

ES2017+ support is very minimal on node 6x. https://node.green/#ES2017
