### ISSUE TITLE
Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.

### ISSUE THREAD

**Issue by dhavaldav** [mongoosastic/mongoosastic#491]
## Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.
- mongoosastic version: 4.5.0
- node version: 12.5.0
- mongoose version: 5.6.8
- elasticsearch version: 7.3.0
## include_type_name TRUE
In ES7.0,we can provide type when creating an index unless setting include_type_name. so i have pass include_type_name "TRUE" on **const typeName = options.typeName+"?include_type_name=true";**  BUT it is give me same error.

Error::

> '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}

**Comment by iiitmahesh** [comment]
@dhavaldav even I am facing the same issue. any update from your side??

**Comment by ronnyvdb** [comment]
Having same issue

**Comment by iiitmahesh** [comment]
As a temporary hack (it worked for my case at least)
I have added below line

> include_type_name: true 

at the line at 87 in _**nodemodules/mongoosastic/lib/mongoosastic.js**_


  ```
 if (exists) {
      return client.indices.putMapping({
        index: indexName,
        type: typeName,
        body: completeMapping,
        include_type_name: true
      }, (err) => {
        cb(err, completeMapping[typeName])
      })
    }
```

**Comment by chaddjohnson** [comment]
@guumaster Can we get this fix into main mongoosastic?

**Comment by guumaster** [comment]
The library still doesn't support Elastic 7. There is a PR open #502 but it doesn't seem a quick migration. Any help and PR are welcome.

**Comment by sachinchhabra-kiwi** [comment]
As per Elastic new Version 

Index creation, index template, and mapping APIs support a new **include_type_name** URL parameter that specifies whether mapping definitions in requests and responses should contain the type name. The parameter defaults to true in version 6.8 to match the pre-7.0 behavior of using type names in mappings. It defaults to false in version 7.0 and will be removed in version 8.0.

Currently, include_type_name at all will result in a deprecation warning.
Here it is - 
 Error: [illegal_argument_exception] Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.
    at respond (/var/www/html/EventBySocial/node_modules/elasticsearch/src/lib/transport.js:315:15)
    at checkRespForFailure (/var/www/html/EventBySocial/node_modules/elasticsearch/src/lib/transport.js:274:7)
    at HttpConnector.<anonymous> (/var/www/html/EventBySocial/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/var/www/html/EventBySocial/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)


statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}',





https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html
