### ISSUE TITLE
Not able to Index _id

### ISSUE THREAD

**Issue by iiitmahesh** [mongoosastic/mongoosastic#494]
Not able to Index  `_id`
```
 _id: {
        type: mongoose.Schema.Types.ObjectId,
        es_indexed: true
      },
```

## Your Environments
- mongoosastic version: 4.5.0
- node version: 10.15.3
- mongoose version: 5.3.12
- elasticsearch version: 7.1

## Expected Behavior

```
GET organizations/_search
{
    "_source": ["name","_id"],
    "query": {
        "match_phrase_prefix": {
            "name" : "abc"
        }
    }
}
```
Output Expected :  

```
hits._source :- name and id 
```
For the above query data, not _id in the source.

**Comment by AxelJunker** [comment]
Mongoosastic filters out the `_id` field because the `_id` field isn't allowed inside a document in Elasticsearch. You will have to change the name of that field to `id`, for example.

This is the error you would get if you try to index a document with an `_id` field:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."
  },
  "status": 400
}
```
