### ISSUE TITLE
Incorrect Mapping Created for Nested Types

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#5]
https://github.com/jamescarr/mongoosastic/issues/79#issue-24758866

> Trying to use ElasticSearch's Facet Terms capability.  To do so, I need to set one of my fields to use the "keyword" analyzer instead of the default.
> 
> Here is my code:
> 
> ```
> var chatSchema = new Schema({
>         cluster: String,
>         time: Number,
>         room: {type:String, es_indexed:true, es_analyzer:'keyword'},
>         user: {type:String, es_indexed:true},
>         message: {type:String, es_indexed:true}
> })
> 
> var clusterSchema = new Schema({
>     name: String,
>     info:{
>         chatCount: Number,
>         start: Number,
>         end: Number,
>         rooms: Array,
>         senders: Array
>     },
>     chat: { type:[chatSchema], es_indexed:true }
> })
> 
> clusterSchema.plugin(mongoosastic);
> ```
> 
> The "analyzer" attribute is not created or passed correctly to ElasticSearch.  Here is what is created in ElasticSearch:
> 
> ```
> mappings: {
>     cluster: {
>         properties: {
>             chat: {
>                 properties: {
>                     message: {
>                         type: string
>                     }
>                     time: {
>                         type: long
>                     }
>                     _id: {
>                         type: string
>                     }
>                     __v: {
>                         type: long
>                     }
>                     cluster: {
>                         type: string
>                     }
>                     user: {
>                         type: string
>                     }
>                     room: {
>                         type: string
>                     }
>                 }
>             }
>             info: {
>                 properties: {
>                     senders: {
>                         type: string
>                     }
>                     start: {
>                         type: long
>                     }
>                     chatCount: {
>                         type: long
>                     }
>                     end: {
>                         type: long
>                     }
>                     rooms: {
>                         type: string
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> A few things to notice:
> - Although I haven't marked the multi-field "info" to be mapped, it is.
> - The "analyzer" attribute is not present on the room field in the chatSchema.
> - The cluster and time fields for the chatSchema (although not marked to be indexed) are being indexed (as well as the _id and __v that I'm assuming is used/managed by Mongoose/MongoDB)
> 
> Using Version: 0.2.6

**Comment by rdubigny** [comment]
On @ztratar 's model I bet start_day.day is indexed in elastic search as well despite it should not. I use a similar model. I didn't managed to make "es_indexed" nor "es_boost" nor "es_cast" to work within nested objects. It's behave like these are simply not read. I haven't tested the other attributes.

**Comment by ksavidetove** [comment]
#28 
#48

**Comment by ksavidetove** [comment]
Referencing here issues #28 and #48 since I develepped a fix and opened a PR to resolve it
