### ISSUE TITLE
Indexing fails when saving documents with populated references

### ISSUE THREAD

**Issue by benFyre** [mongoosastic/mongoosastic#515]
## Your Environments
- mongoosastic version: 4.5.1
- node version: 8.9.4
- mongoose version: 5.4.22
- elasticsearch version: 7.1.1

## Expected Behavior

Example Schema
```
var User = new Schema({
    name: {type: String, es_indexed: true}
  , email: String
  , city: String
  , role: {
      type: Schema.Types.ObjectId,
      ref: 'Role'
  }
})
```
Saving this entity through mongoose should index role as a stringified ObjectId regardless of whether or not role has been populated prior to saving as I have not defined an es_schema on the role field.
## Actual Behavior

Saving without role being populated works correctly.

Populating "role" on a user and then saving the user fails as it now attempts to index the entire populated role instead of just the stringified _id

Error is due to this code section
```
    name = outModel.constructor.name
    if (name === 'ObjectID') {
      return outModel.toString()
    }
```
It will return the stringified ObjectId if the field is of type ObjectId, but when it is of type "model" instead of (as it is after populating) it will fail.
## Proposed Changed
Update above code block to be
```
    name = outModel.constructor.name
    if (name === 'ObjectID') {
      return outModel.toString()
    }
    if (name === 'model' && mapping.type === 'text' && outModel._id) {
      return outModel._id.toString();
    }
```
name equaling 'model' means that outModel is a mongoose model (and has an _id) and mapping.type equaling 'text' means that we don't want the full object, but rather just the stringified _id as we didn't defined an es_schema in the original schema.

**Comment by ddtraceweb** [comment]
i have same problem.
