### ISSUE TITLE
develop branch is missing

### ISSUE THREAD

**Issue by zhfahan77** [mongoosastic/mongoosastic#522]
I have gone through the [CONTRIBUTING.md](https://github.com/mongoosastic/mongoosastic/blob/master/CONTRIBUTING.md). According to the MD it says to cut a head of `develop` branch to further create `feature/*` branch. However, there isn't any `develop` branch.

So I here propose

either
- we create a develop branch

or 
- we update `CONTRIBUTIN.md` to mention to cut feature branches from master.

**Comment by guumaster** [comment]
Thanks for pointing this out. I've uploaded a `develop` branch.
