### ISSUE TITLE
Subdocuments automatically indexed, can't unindex

### ISSUE THREAD

**Issue by BigFax** [mongoosastic/mongoosastic#534]
Let's take two basic mongoose schemas :

```javascript
var childSchema = new Schema({
  path: {
    type: String,
    required: true
  },

  name: { 
    type: String,
    minlength: 2,
    maxlength: 50
  },

  description: {
    type: String,
    trim: true,
    minlength: 10,
    maxlength: 5000
  },

  created_at: {
    type: Date,
    required: true
  },

  // etc...
});

var parentSchema = new Schema({
  title: { 
    es_indexed: true,
    type: String,
    minlength: 2,
    maxlength: 50
  },

  content: {
    es_indexed: true,
    type: String,
    trim: true,
    minlength: 10,
    maxlength: 5000
  },
  
  created_at: {
    type: Date,
    required: true
  },

  // Array of subdocuments
  children:[{
    type: childSchema,
  }],

  // etc...
});
```

Elasticsearch will automatically indexed `title` and `content` from `parentSchema` and not other fields. This is the expected behavior.

Now, `children` will be also fully indexed (path, name, description, created_at...).
How can I don't have my children to be automatically fully indexed into ElasticSearch ?

I tried to put `es_indexed: false` on children, on each `childSchema` fields or to have `indexAutomatically` option to `false`, but it doesn't works.
(Putting `es_indexed: false` on a `childSchema` field won't add it to the ES index, but the `children` field itself will still be indexed)

Maybe related to #145 #214 

Thank you in advance.

## Your Environments
- mongoosastic version: 4.5.1
- node version: 13.7.0
- mongoose version: 5.9.6
- elasticsearch version: 7.3.0

## Expected Behavior
To me, subdocuments should not be indexed by default. 
Should have a way to change the default behavior.

## Actual Behavior
Subdocuments are automatically fully indexed by default and i don't find any way to change this behavior.

**Comment by BigFax** [comment]
One solution is to change the syntax,

From :
```javascript
children: [{
  type: childSchema,
}]
```

To :
```javascript
children: {
  es_indexed: false,
  type: [childSchema],
}
```

However, i still think it shouldn't index subdocuments by default and it should works  with the other syntax which is the one use in mongoose documentation.

**Comment by guumaster** [comment]
Hi @BigFax, thanks for your contribution. If that solution fix the issue you can open a PR with it.

**Comment by BigFax** [comment]
Hi @guumaster, the solution is a modification in my schema, not in the module itself. 

However, I don't think the module works as it should for the reasons I mentionned above. When I will have time, I will investigate the source code of the module itself.

**Comment by rturk** [comment]
@BigFax IMO we should index subdocuments as they are a part of the document. You either explicitly index all of the document (Default behavior) or individually set fields that will or not be indexed

**Comment by BigFax** [comment]
@rturk Indeed it should be indexed by default, but only if `es_indexed: true` is not present in the schema definition. 

The expected behavior defined in the documentation is that all fields are indexed by default (subdocument too), but if `es_indexed: true` is defined somewhere, only fields with `es_indexed: true` are indexed. 

In this situation, `es_indexed: true` is defined in some fields, so only fields with `es_indexed: true` should be indexed, subdocument or not because as you said, subdocument are part of the document, like other fields.

**Comment by rturk** [comment]
@BigFax makes sense. 
Maybe if we add more corner cases tests this issue will be more clear to debug
