### ISSUE TITLE
New npm version

### ISSUE THREAD

**Issue by guumaster** [mongoosastic/mongoosastic#54]
The repo is tagged with new version 2.0.7, and it is ready to publish. Could you please publish it, or give access to collaborators to publish?

Docs on npm access is [here](https://docs.npmjs.com/cli/owner), ex:

```
npm owner add guumaster mongoosastic
```

**Comment by taterbase** [comment]
You've been added to the npm package, feel free to publish it. Thanks @guumaster!

**Comment by guumaster** [comment]
Thanks for the trust. I'm working with a test that is failing on travis due to a "not-really-realtime" feature of Elasticsearch after deletion.  But the library works perfectly.

**Comment by taterbase** [comment]
Yes, getting tests to pass on Travis is frustrating with elastic search, I often have to keep retrying the test until it works :disappointed:
