### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (null)

### ISSUE THREAD

**Issue by ddtraceweb** [mongoosastic/mongoosastic#541]
Hello, i have this error, have you an idea ?

Jul 20 15:14:44 sml-apig-05 api[53304]: events.js:306
Jul 20 15:14:44 sml-apig-05 api[53304]: throw err; // Unhandled 'error' event
Jul 20 15:14:44 sml-apig-05 api[53304]: ^
Jul 20 15:14:44 sml-apig-05 api[53304]: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (null)
Jul 20 15:14:44 sml-apig-05 api[53304]: at EventEmitter.emit (events.js:304:17)
Jul 20 15:14:44 sml-apig-05 api[53304]: at /data/app/prod.graphcomment.com/api/node_modules/mongoosastic/lib/mongoosastic.js:723:23
Jul 20 15:14:44 sml-apig-05 api[53304]: at respond (/data/app/prod.graphcomment.com/api/node_modules/elasticsearch/src/lib/transport.js:370:9)
Jul 20 15:14:44 sml-apig-05 api[53304]: at checkRespForFailure (/data/app/prod.graphcomment.com/api/node_modules/elasticsearch/src/lib/transport.js:306:7)
Jul 20 15:14:44 sml-apig-05 api[53304]: at HttpConnector.<anonymous> (/data/app/prod.graphcomment.com/api/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
Jul 20 15:14:44 sml-apig-05 api[53304]: at IncomingMessage.wrapper (/data/app/prod.graphcomment.com/api/node_modules/lodash/lodash.js:4949:19)
Jul 20 15:14:44 sml-apig-05 api[53304]: at IncomingMessage.emit (events.js:327:22)
Jul 20 15:14:44 sml-apig-05 api[53304]: at endReadableNT (_stream_readable.js:1221:12)
Jul 20 15:14:44 sml-apig-05 api[53304]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Jul 20 15:14:44 sml-apig-05 api[53304]: code: 'ERR_UNHANDLED_ERROR',
Jul 20 15:14:44 sml-apig-05 api[53304]: context: null
Jul 20 15:14:44 sml-apig-05 api[53304]: }

- mongoosastic version: 4.6.0
- node version: 12.18
- mongoose version: 5.9.22
- elasticsearch version: x.y.z

**Comment by ddtraceweb** [comment]
du to error in model.

**Comment by rilias92** [comment]
Hi @ddtraceweb, I think that I am facing the same issue... Could you more specific about the error?

**Comment by ddtraceweb** [comment]
in my case, it's when elastic search model is not the same of the document you send to be indexed. You must look in error log of ElasticSearch...

**Comment by rilias92** [comment]
Ok great...Thank you very much!!
