### ISSUE TITLE
Singleton or dependency injection pattern

### ISSUE THREAD

**Issue by tsturzl** [mongoosastic/mongoosastic#57]
Why don't you use a singleton or dependency injection pattern? For each schema I'm creating a new elasticsearch client. Though elasticsearch isn't a persistent connection I find it odd that each time I use this plugin on a schema I'm creating an entirely new elasticsearch client.

I basically have to load my config file, grab the connection info out, and pass it as an option for each schema. Why not just have `mongoosastic.connect("host", port)`, call it once and reuse that same elasticsearch client. You've gone to the extent of using the _nop_ module, yet you initiate a new client for each schema. It's not terribly inefficient, but its definitely not convenient. As I typically only have a single elasticsearch cluster for an entire project, but I might have multiple types/indices.

This approach would be similar to how mongoose does it themselves. Is there any reason why this hasn't been done? You also don't allow passing multiple hosts. Is there any reason for this?

**Comment by guumaster** [comment]
Hi, since version 2.1.0 you could use an existing client as parameter to the plugin. Also, is you use `hosts` in the plugin options you can connect to multiple hosts, in the same way you would with the Elasticsearch client.

The proposal on re-using the connection sounds good. Also, remember that the project accepts pull requests :+1:

**Comment by tsturzl** [comment]
Right, I just wanted to inquire before sending a PR. I have the project forked. I'm hoping to have it done by next week. The only problem is this won't be backwards compatible. As singleton require prototype object, and mongoosastic currently uses closure objects. So I can't provide an instanced object. What I'm doing is wrapping the Mongoosastic object in a prototype object, then passing a `new` singleton object to `module.exports` this singleton has methods: `.connect(host/s)`, `.plugin(schema,options)`. However, you can `var mongoosastic = require('mongoosastic').plugin` and you can pass connection settings as is currently done.

Is this going to be a problem? Because this will break the current pattern, though you can use the work around stated above.

So new:

```
var mongoose     = require('mongoose')
  , mongoosastic = require('mongoosastic')
  , Schema       = mongoose.Schema

mongoosastic.connect('host:9200');

var User = new Schema({
    name: String
  , email: String
  , city: String
})

User.plugin(mongoosastic.plugin);
```

Old:

```
var mongoose     = require('mongoose')
  , mongoosastic = require('mongoosastic')
  , Schema       = mongoose.Schema

var User = new Schema({
    name: String
  , email: String
  , city: String
})

User.plugin(mongoosastic, {host: 'host:9200'});
```

Work around:

```
var mongoose     = require('mongoose')
  , mongoosastic = require('mongoosastic').plugin
  , Schema       = mongoose.Schema

var User = new Schema({
    name: String
  , email: String
  , city: String
})

User.plugin(mongoosastic);
```

**Comment by guumaster** [comment]
Well maybe that is very different from the current usage. Passing an existing client would also solve the problem in simple way without breaking the current form.

Maybe there is an easier way to achieve this and don't break compatibility

**Comment by tsturzl** [comment]
I have the changes made for singleton pattern on [my fork](https://github.com/tsturzl/mongoosastic). In order to preserve the client between `require()`'s without a singleton pattern, globals would be the only way to pass client between each module instance. I feel like that could be dirty. I like your approach better, I see your revision now. I'll leave my fork alone for now, but leave it up as a reference. 

I haven't re-written the documentation for it, but I adapted the tests. So if your curious as to how it works, I recommend looking at the tests for now.
