### ISSUE TITLE
update `jest` to latest version

### ISSUE THREAD

**Issue by guumaster** [mongoosastic/mongoosastic#591]
when using `jest@latest` (currently v27) test suites brake with this error: 

```
 Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise.
```

several tests needs to be reviewed.

**Comment by yahiakr** [comment]
The new 27.x version does not support done callback and async test simultaneously (see this: https://github.com/facebook/jest/issues/10529).

As we are using both of them in event-based tests (e.g: to test synchronize method), we need to think of a way to tests those methods with one paradigm (done callback or async).
