### ISSUE TITLE
synchronize function not working as expected

### ISSUE THREAD

**Issue by vmorgado** [mongoosastic/mongoosastic#592]
synchronize function seems to not be working as advertised. When we set the bulk options it still synchronizes by indexing one by one instead of the designed batch size. 

## Your Environments
- mongoosastic version: 5.0.0
- node version: 14.18.1
- mongoose version: 6.1.4
- elasticsearch version: 7.4.0

## Expected Behavior
When running synchronize method with the bulk import options enabled we should be able to import to the elasticsearch as a bulk and not one by one. 

## Actual Behavior
Seems to be pushing 1 by 1 to the elasticsearch and it is makes no sense for big datasets, for example our dataset with just 1 000 000 entries takes over two days to import using the sync method.

**Comment by yahiakr** [comment]
Hi @vmorgado,

Thank you for opening this issue. I tried to re-debug the code, and re-run the synchronize tests with different options, the function is seems to work as expected.

Could you please share a code snippet so we can reproduce the bug?
Thanks.

**Comment by vmorgado** [comment]
Hey yahiakr, thanks for the quick answer.

The synchronise does not work as advertised by the documentation:

``` You can also specify bulk options with mongoose which will utilize Elasticsearch's bulk indexing api. This will cause the synchronize function to use bulk indexing as well. ```

Altho if you look into your code for the synchronize function, the code there is not calling your bulk import code.
It does read the options, creates a stream that handles the mongo query by batch size, but the actual import is done one by one.

You would want to create that stream and use your bulkAdd function to build the batch to sent to ElasticSearch.

**Comment by yahiakr** [comment]
Hi,

In `synchronise` method, we get the batch from mongo stream, then we enable “re-saving” of the document in case you have custom pre/post hooks to run before saving it to ES (this is optional, check `saveOnSynchronize` option in the documentation).

In case `saveOnSynchronize` is `false`, we call the `postSave()` method (e.g: to populate data in necessary), but with the `bulk options` already set. If you try to debug the `postSave()` method, you find that we start filling the `bulkBuffer` (if bulk options are set) and we call the `flush()` method each time the `bulkBuffer` size reach the specified option.

The method work as expected! try to debug the `bulkBuffer` and how many times the `flush()` method is called.

If you can share a code snippet that re-produce the bug, please do it.
