### ISSUE TITLE
need bulkAdd method to be exposed so we can use it on the model , as we are facing problem with synchronize method

### ISSUE THREAD

**Issue by Alaa-Mahmoud** [mongoosastic/mongoosastic#600]
We need to import and existing MogoDB collection to elastic-search when using the synchronize method on the model it takes a lot of time like almost 2 days and didn't finish or get close our dataset is more than 1 Million document but when we exposed the bulkAdd method and use it instead of the synchronize method all dataset filled into elastic-search in 15 - 20 minutes and this is a reasonable time for us what we need because we need  from. your side is to expose the bulkAdd method so we can access it on the model directly until you investigate with the synchronize method behaviour with large/massive datasets 
## Your Environments
- mongoosastic version: 5.0.0
- node version: 14.18.1
- mongoose version: 6.1.4
- elasticsearch version: 7.4.0

## Expected Behavior
when having existing larage/massive dataset needed to be imported into elasticsearch using synchronize method on the model 
it should do it in reasonable time like as we experimented exposing the bulkAdd method and did it in. 15 - 20 minutes.
## Actual Behavior
when using synchronize method to import large/massive datasets like ours more than 1 Million document it should do it inn reasonable time we run it for almost 2 days and didn't finished or even get closed , but when we exposed the bulkAdd method it did the job in 15 - 20 minutes

**Comment by vmorgado** [comment]
Same as this, https://github.com/mongoosastic/mongoosastic/issues/592 .
Unfortunately is not possible to create MR to this repo.
Exporting the bulkAdd and using it instead works as intended.

**Comment by Alaa-Mahmoud** [comment]
@yahiakr @guumaster  please help and advice.

**Comment by yahiakr** [comment]
Hi @Alaa-Mahmoud,

Thank you for opening this issue.

If you think that exposing the `bulkAdd` method will solve the problem "temporarily", feel free to open a PR and i will merge it. Meanwhile, if you can debug the problem/bug, it would be great to fix the `synchronize` method so we don't need to use the `bulkAdd` method.

I will try to find some time to debug and fix the problem. Any contribution would be greatly appreciated :)

**Comment by vmorgado** [comment]
I can't push a branch against this repo, perhaps we need contributor rights (?)

**Comment by Alaa-Mahmoud** [comment]
@yahiakr i did follow the contribution guideline and when i try to push my branch i get

fatal: unable to access 'https://github.com/mongoosastic/mongoosastic.git/': The requested URL returned error: 403

please advice  , do i need a contribution access or something ?

**Comment by Alaa-Mahmoud** [comment]
> I can't push a branch against this repo, perhaps we need contributor rights (?)

same issue

**Comment by guumaster** [comment]
@Alaa-Mahmoud @vmorgado only Contributors can push directly to branches. But you can fork an create a PR as usual, if you need more info on that you can check the GitHub docs on this page [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
