### ISSUE TITLE
The ElasticSearch result does not contain body - it should be just res.hits

### ISSUE THREAD

**Issue by woon-werd** [mongoosastic/mongoosastic#605]
https://github.com/mongoosastic/mongoosastic/blob/49ff5ba9daf6704f8ac7adcc83392c8033d33687/lib/utils.ts#L105

**Comment by alexandermakalov** [comment]
I use elasticsearch 8.3.2 and API 8.3
`        this.esClient()
            .bulk({
            body: bulkBuffer,
        })
            .then((res) => {
            if (res.body.items && res.body.items.length) {
                for (let i = 0; i < res.body.items.length; i++) {
                    const info = res.body.items[i];
                    if (info && info.index && info.index.error) {
                        this.bulkError().emit('error', null, info.index);
                    }
                }
            }
        })`

res doesn't have body parameter. Only items so I've rollebacked to 7.10

**Comment by nitzan-blink** [comment]
having this issue as well, when I use model.synchronize(), I get errors that "res" doesn't have "body" property.
file: bulking.js, function: flush().

```
            if (res.body.items && res.body.items.length) {
                for (let i = 0; i < res.body.items.length; i++) {
                    const info = res.body.items[i];
```

**Comment by yahiakr** [comment]
Hey! Thanks for opening this issue.

The reason behind this error is that `v5` of the package is compatible with `v7.x` of Elasticsearch, as it use `@elastic/elasticsearch:7.x.x` under the hood.
The `v4.x` of `mongoosastic` is compatible with `v6.x` of Elasticsearch, etc ..

I would say it's my fault, I need to add this compatibly matrix in the `README.md`, sorry for that.

We will try to find some time and work on publishing a new version that would be compatible with the newer version of ES.
And of course, it would be great if we can find more contributor to this project.

**Comment by simo385** [comment]
Hi everybody,

@yahiakr When do you think to release ES 8 compatibility?

Thanks,
Simone
