### ISSUE TITLE
The new document can not be searched after it accepts es-indexed event

### ISSUE THREAD

**Issue by goddyZhao** [mongoosastic/mongoosastic#63]
Here is my case:

1. Add new doc and make it listen on `es-indexed` event to make sure the index is built in es
2. Then search it immediately but the search result does not contain the new one

I can get the new one if I search it after 1-2 seconds later. So, I guess if the `es-indexed` event does not make sure building index has been completed?

**Comment by guumaster** [comment]
Elasticsearch is "near-realtime" so that delay is to be expected. If you look the tests in this project you will see that there is a delay between indexing and search. You can read more about it [here](http://www.elastic.co/guide/en/elasticsearch/guide/master/near-real-time.html)
