### ISSUE TITLE
How to query a post by tag?

### ISSUE THREAD

**Issue by janryWang** [mongoosastic/mongoosastic#65]
This is my tag 
```
{
  id:"xxxxx"
  name:"xxxxx"
}
```
This is my post
```
{
    id:"xxxx",
    title:"xxxxx",
    content:"xxxxx",
    tags:[tag_id,....]
}
```
I want query a post's list by tag's name. Does it support this feature?

**Comment by guumaster** [comment]
You can't do only one search by tags with that models. You would need to get the tags ids and then query your posts with that array.
