### ISSUE TITLE
Return promises instead of callback

### ISSUE THREAD

**Issue by felixsanz** [mongoosastic/mongoosastic#68]
In Mongoose 4.0, almost all (if not all) methods returns a Promise. How factible is this change?

**Comment by guumaster** [comment]
We should check how Mongoose does that and try to do it also.

**Comment by PLEEROCK** [comment]
+1

**Comment by felixsanz** [comment]
This makes the job meanwhile: (not tested yet!)

```js
    const searchPromise = function* searchPromise(query, options) {
      return new Promise((resolve, reject) => {
        this.app.models.post.search(query, options, function(err, data) {
          if (err !== null) {
            return reject(err);
          }

          resolve(data);
        });
      });
    }.bind(this);
```

Consuming it as: (example)

```js
    const data = yield searchPromise({
      'filtered': {
        'query': {
          'match': { '_all': query }
        }
      }
    }, { from: skipFrom, size: resultsPerPage, hydrateOptions: { select: '_id published_at name' } });
```

**Comment by guumaster** [comment]
At the moment, I'd prefer an approach similar to Mongoose promises and not a ES6 that introduce a transpiler in the mix. And probably we should maintain compatibility with the current implementation. Is not an easy patch. 

PR are very much welcome :)

**Comment by felixsanz** [comment]
This? -> https://github.com/Automattic/mongoose/blob/master/lib/promise.js

I can submit a PR with ES6 promises but no idea how mongoose implements it :(

Anyway they increased a mayor version (2.x to 3.x) to include promises, so you should upgrade the lib version and it will be a breaking change as mongoose did

**Comment by jspizziri** [comment]
+1

**Comment by mrpatiwi** [comment]
+1

**Comment by mrpatiwi** [comment]
My current approach:

```js
const mongoose = require('mongoose');
const mongoosastic = require('mongoosastic');
const Promise = require("bluebird");

const UserSchema = new Schema({
  /*...*/
});

UserSchema.plugin(mongoosastic);

const User = mongoose.model('User', UserSchema);
User.search = Promise.promisify(User.search, { context: User });
```

**Comment by juanpujol** [comment]
+1

**Comment by TD-Stanley** [comment]
+1

**Comment by guumaster** [comment]
Now that we have a green pipeline again, we can explore a refactor or rewrite with async/await instead of callbacks.

Feel free to open PRs on `develop` branch.
