### ISSUE TITLE
Removing

### ISSUE THREAD

**Issue by agjs** [mongoosastic/mongoosastic#70]
Hey guys. When we remove a document from our mongo, how do we remove the reference from Elastic as well ? In the official example, there is only a documentation about saving a file, what about deleting one ? Or do we also use doc.on('es-indexed') while removing too (findOneAndRemove). 

Thanks in advance

**Comment by agjs** [comment]
Anyone ?

**Comment by francesconero** [comment]
It's not documented but, it should be automatically be removed from elastic as long as you trigger the mongoose middleware (so you can't use a findOneAndRemove for example).

As you can see in the code:

```javascript
/**
   * Use standard Mongoose Middleware hooks
   * to persist to Elasticsearch
   */
  function setUpMiddlewareHooks(schema) {
    schema.post('remove', function(doc) {
      setIndexNameIfUnset(doc.constructor.modelName);

      var options = {
        index: indexName,
        type: typeName,
        tries: 3,
        model: doc,
        client: esClient
      };

      if (bulk) {
        bulkDelete(options, nop);
      } else {
        deleteByMongoId(options, nop);
      }
    });

    /**
     * Save in elasticsearch on save.
     */

    schema.post('save', function(doc) {
      doc.index(function(err, res) {
        if (!filter || !filter(doc)) {
          doc.emit('es-indexed', err, res);
        }
      });
    });
  }

};
```

The post 'remove' hook deletes the index from elastic.

**Comment by guumaster** [comment]
As @francesconero mention, the elastic remove process happens in the post save hook. Mongoose only execute hooks on explicit `.save()` or `remove()` and not in `findOneAndUpdate()` or  `findOneAndRemove()`
