### ISSUE TITLE
not_analyzed parameter is not applied when indexing fields

### ISSUE THREAD

**Issue by davidsandoz** [mongoosastic/mongoosastic#76]
Hi, I am indexing a mongoose model into Elasticsearch by specifying the fields using `es_indexed: true`, which worked fine.

Now I want some of those fields not to be analyzed by using the `index: 'not_analyzed'` option, but it doesn't work.

I ran `GET /actions/_mapping` in Elasticsearch to check the mapping, and the option is not shown. Therefore I guess that mongoosastic is not passing it.

I also tried to delete the index from Elasticsearch to ensure that it takes my edits into consideration, but it didn't change neither.

If I manually enter the index using `PUT /actions`, then it works, but the goal is to have it in the schema declaration, as below.

```
var actionSchema = exports.Schema = mongoose.Schema({
  published: {
    type: Date,
    default: Date.now,
    es_indexed: true
  },
  actorUser: {
    type: ObjectId,
    ref: 'User',
    es_indexed: true
  },
  actor: {
    type: activityObject,
    es_indexed: true
  },
  pictureUrl: String,
  verb: {
    type: String,
    es_indexed: true,
    index: 'not_analyzed'
  },
  object: {
    type: activityObject,
    es_indexed: true
  },
  target: {
    id: {
      type: String,
      es_indexed: true
    },
    displayName: {
      type: String,
      es_indexed: true,
      index: 'not_analyzed'
    },
    objectType: {
      type: String,
      es_indexed: true
    },
    image: String,
    url: String
  },
  path: {
    type: String,
    es_indexed: true
  },
  recipients: [{
    type: ObjectId,
    ref: 'User'
  }]
});
```

Am I doing something wrong ? What should I do to make it work?

Thanks!

**Comment by guumaster** [comment]
All Elasticsearch properties must be prefixed with "es_". Try changing `index: 'not_analyzed'` to `es_index: 'not_analyzed'`

**Comment by aredo** [comment]
@guumaster i also have been using like what you mention, but it not working.

**Comment by guumaster** [comment]
@aredo I'm currently using this feature and works properly after adding `es_index: 'not_analyzed'`. Try recreating the index and check your elasticsearch.

**Comment by davidsandoz** [comment]
@guumaster Thanks for your answer. I tried your suggestion but it's not working for me. The parameter is still not recognized by Elasticsearch, even after completely erasing the index and recreating it.

@aredo So, you are facing the same problem? Are you also manually entering the index to make it work or do you have another workaround?

**Comment by davidsandoz** [comment]
@guumaster Do you have an idea of where else I should try to look to fix that problem?

**Comment by guumaster** [comment]
I've created a simple test and was able to reproduce this problem. It seems that we need to check the "magic" behind `mapping-generator.js`

**Comment by chakravarthysm** [comment]
I am also facing the same problem, I've tried both index: 'not_analyzed' and es_index: 'not_analyzed' , but still its not working.

**Comment by guumaster** [comment]
I'm using it and it works, but it seems in some cases it doesn't. In my working example, I assure you that the correct name is `es_index`. 

We have to compare and figure out why sometimes it doesn't add the `not_analyzed` property.

**Comment by aredo** [comment]
@guumaster can you past to us how you define your Schema when using mongoosastic

**Comment by guumaster** [comment]
This is part of my working schema. With analized and not_analized indexed data.
```
MessageSchema = new mongoose.Schema({
  ts: {type: Date, default: Date.now, required: true},  
  details: {
    title: {type: String, trim: true, match: /\S+/, required: true, es_indexed: true },
  },
  scope: {
    nbhd: {
      city: {type: String, trim: true, es_indexed: true, es_index: 'not_analyzed'},
      zipCode: {type: String, trim: true, es_indexed: true, es_index: 'not_analyzed'},
   }
 }
}, {versionKey: false});

MessageSchema.plugin(mongoosastic);

var model = mongoose.model('Message', MessageSchema);
```

**Comment by eferesen** [comment]
Greeting,
I am having a similar issue.  Perhaps my mapping is incorrect.  I am trying to index a array field with not_analyzed.  I followed this example: https://www.elastic.co/guide/en/elasticsearch/guide/current/aggregations-and-analysis.html

The mapping of the field 'instStat' after indexing is as follow:
"instStat": {
"type": "string"
}

This should not be the case.  It is analyzing and breaking up words. I want it to aggregate by the entire phrase. How can I get around this?  

Here is the schema:
var UserSchema = new Schema({
  email: String,
  acadPlan: [],
  institutionCount: Number,
  courseCount: Number,
  lastPage: String,
  instStat:  {type: String,
             es_type: 'multi_field',
             es_fields : {
                name : { es_type: 'string', es_index: 'not_analyzed'}
            }
        },
  created: { type: Date, default: Date.now }
});

UserSchema.plugin(mongoosastic, {
  index : 'transfer',
  type : 'users'
});
var User = mongoose.model('User', UserSchema, 'users');

**Comment by prasadbhosale** [comment]
I was also facing this problem but finally I got a work around for it. You can add 'not_analyzed' in mongosastic library.

ex.
go node_modules->mongoosastic->lib->mapping-generator.js

In a function getCleanTree
find and replace this code

else if (value === String || value === Object || value === Date || value === Number || value === Boolean || value === Array) {
                cleanTree[field] = {};
                cleanTree[field].type = type;
                if (cleanTree[field].type === 'string') {
                    cleanTree[field].fields = {
                        raw: {
                            type: 'string',
                            index: 'not_analyzed'
                        }
                    };
                }
            }

**Comment by francesconero** [comment]
I managed to get it working by calling [createMapping](https://github.com/mongoosastic/mongoosastic#creating-mappings-on-demand) after the schema definition. I don't know if this should be required or not, I can't figure it out from the docs.

**Comment by nschloe** [comment]
I've got the same issue, and worked around it the same way that @francesconero did: By calling `createMapping` after schema definition. This feels kind of shaky though.

**Comment by michelem09** [comment]
Is it possible since ES 2.2 the `multi_field` in Mongoosastic doesn't work anymore due to this breaking change? https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html

**Comment by anton6** [comment]
Thanks guumaster, worked for me. I am also calling createMapping after schema definition by the way.

**Comment by jonnadams** [comment]
I seem to be getting this issue to even after calling createMapping. Does anyone have a full working code sample that I could take a look at?

**Comment by zorend** [comment]
I used  lang:{type:String,es_indexed:true,es_index:'not_analyzed'}, if you previously created the index without not_analyzed, delete the index using curl -XDELETE 'http://localhost:9200/indexname/'

**Comment by danielmeng07** [comment]
Why is 'not analyzed' even necessary? According to the documentation: specifying `es_indexed: true` In this case only the name field will be indexed for searching. Also, you guys are saying to set using `es_index` but [documentation](https://www.npmjs.com/package/mongoosastic) is saying `es_indexed`, which is it?

**Comment by d4goxn** [comment]
@danielmeng07 `es_indexed` seems to be correct, not `es_index`.

**Comment by jemliF** [comment]
I am having the same issue, and I will go back to ES native module cause this plugin is not very robust and not well documented and supported. I was wasting time trying this plugin, this issue was reported more than one year ago and until this moment, you still unable to fix it!

**Comment by wedgemartin** [comment]
Also seeing this with latest ES 5.4 and mongoosastic 4.3.0. Just seems to igonre it, and digging into the source, I don't see where this would've ever worked.
