### ISSUE TITLE
Index referenced documents

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#8]
https://github.com/jamescarr/mongoosastic/issues/101#issue-32205453

> I'm attempting to index referenced documents. (Without making them sub-documents)
> 
> For example;
> 
> ```
> var Author = mongoose.Schema({
>     name: { type: String }
> }):
> 
> var Page = mongoose.Schema({
>     title: { type: String },
>     author: { type: ObjectId, ref: 'Author' }
> });
> ```
> 
> After getting indexed this becomes something like this;
> 
> ```
> "author": {
>     _bsontype: "ObjectID",
>     id: "SYæSþ\n®àÊF$"
> },
> ```
> 
> Is there anyway to index the full referenced object instead of just the ObjectId?

**Comment by theolampert** [comment]
@taterbase were you able to figure this one out?. I've been trying a work around by populating pre save and manually entering that object into es but so far hasn't been successful.

**Comment by reilg** [comment]
Was this ever done?

**Comment by gsantome** [comment]
this feature is really really important to have a good integration with mongoose because one of the cool feature on mongoose is the .populate.

**Comment by ravishivt** [comment]
+1

**Comment by isayme** [comment]
The feature is supported now~

PR https://github.com/mongoosastic/mongoosastic/pull/147/files
Document https://github.com/mongoosastic/mongoosastic#indexing-mongoose-references
