### ISSUE TITLE
elastics indexes aren't updated when mongodb objects are updated

### ISSUE THREAD

**Issue by PLEEROCK** [mongoosastic/mongoosastic#82]
I've tried to update already created object (via mongoose of course), but realized that indexes in the elastics aren't updated, and I cant find my updated records any more. Why such important feature is not implemented, or do I miss something?

**Comment by PLEEROCK** [comment]
however I can update object and call .index manually

**Comment by guumaster** [comment]
How are you updating your data? Currently mongoosastic only sync the index on `save()` and `remove()`. If you use another mongoose method, you need to call `index()` explicitly.

**Comment by PLEEROCK** [comment]
I do updates using ```findOneAndUpdate``` method

**Comment by isayme** [comment]
@PLEEROCK this problem fixed in [pull 97](https://github.com/mongoosastic/mongoosastic/pull/97)

**Comment by raeesaa** [comment]
Is there any fix for mongoose `update` function? I have used it at most of the places in my application and indexes are not getting updated for records updated using `update` function.

**Comment by johannds** [comment]
I'm finding that the records are not being removed from ES when I delete documents using .remove(). Anyone else seeing this?

**Comment by gmaniac** [comment]
Was this added? I am doing `findOneAndUpdate()` but it does not seem to re-index. 

I am assuming we still have to do what @guumaster mentioned

> you need to call index() explicitly.
