### ISSUE TITLE
Search with aggregations

### ISSUE THREAD

**Issue by g-lf** [mongoosastic/mongoosastic#83]
Hello,

With 0.5.0 I galdly used search method with aggregations and filters.
This was possible because the query passed to the search method was a full object passed on to ES.
esClient.search(query...

From 2.0.0 on, this is no more possible since the 'query' term is hardcoded :
body: {
  query: query
}

Do you plan to provide a way to pass the whole query body as a param instead of allowing juste the query content ?
It would help me upgrade, since I really do need my aggs and filters.

Thanks

**Comment by guumaster** [comment]
We may improve this. Meanwhile, remember that you can acccess the full esClient and do any search you want.

Instead of `MyModel.search(...)` use `MyModel.esClient.search(...)`

**Comment by g-lf** [comment]
Thanks for the tip, it would indeed do the trick
Unfortunately I could not get it work : MyModel.esClient returns undefined
I guess I am missing something here ?
Any light appreciated (tried 2.1.3 on top of mongoose 3.8.2)

**Comment by guumaster** [comment]
The plugin doesn't expose the index name. You can either pass the index name to use as parameter `index: "INDEX_NAME"` or use the model name lowercase.

**Comment by JasonMore** [comment]
I need aggregations too so I'll work on this and see if I can come up with something

**Comment by guumaster** [comment]
Ok, I think that this plugin should focus more on reflecting data from Mongo to ES and not so much in complex searches. If you everything mapped as you want with mongoosastic, complex queries not supported by `search()` method provided by the plugin can be acheived perfectly with `elasticsearch-js` library. What do you think?

**Comment by JasonMore** [comment]
@guumaster yeah thats what we are doing now. The only thing that is really missing is pulling out the index names from mongoosastic. Code example:

```
productSchema.plugin(mongoosastic, {index: `product-map.products`, esClient: elasticSearch});
var Product = mongoose.model('Product', productSchema);
```

```
client.search({
		index: 'product-map.products',
		type: 'product',
		body: {
			...
		}
	})
```

It would be nice if I could for example do something like this:

```
client.search({
		index: Product.es_index,
		type: Product.es_type,
		body: {
			...
		}
	})
```

What do you think of that?

**Comment by isayme** [comment]
closed refer https://github.com/mongoosastic/mongoosastic/pull/249
