### ISSUE TITLE
Synchronize high memory usage

### ISSUE THREAD

**Issue by jdelibas** [mongoosastic/mongoosastic#84]
I am running a `model.synchronize()` and listening the stream events.

There are over 2000+ documents that need to be indexed to ES. The indexing is fine.
But the application memory usage goes from ~80mb to ~360mb and stays there.

```
var syncStream = Model.synchronize();
var count = 0;

syncStream.on('data', function(err, doc) {
    count++;

    if (err) {
        console.log.log('products index count = ' + count + ' insert error');
    }
});

syncStream.on('close', function() {
    console.log('products indexed ' + count + ' documents!');
});

syncStream.on('error', function(err) {
    console.log('error replicating products to elastic search');
});

```

The moment I take this block out then the memory usage holds at ~80mb.

**Comment by jdelibas** [comment]
`/lib/mongoosastic.js#schema.statics.synchronize()`
```
    stream.on('data', function(doc) {
      counter++;
      doc.save(function(err) {
        if (err) {
          return em.emit('error', err);
        }

        doc.on('es-indexed', function(err, doc) {
          counter--;
          if (err) {
            em.emit('error', err);
          } else {
            em.emit('data', null, doc);
          }

        });
      });
    });
```

`doc.save` seems to be the culprit as far as I can tell. Still looking into how the library works. But removing that function reduces the memory overhead. Something in save is leaving references behind.

**Comment by jdelibas** [comment]
:+1:

**Comment by guumaster** [comment]
#85 merged, should solves this issue... or reopen.
