### ISSUE TITLE
model.Synchronize() is not working for sync existing documents.

### ISSUE THREAD

**Issue by kishankachchhi** [mongoosastic/mongoosastic#86]
I am using mongodb 3.0.3 & elasticsearch 1.6
Mongoose:4.0.5
Mongoosastic:3.1.2
I am calling the function 
var stream = model.synchronize().
Where the stream object getting the value like { domain: null, _events: {}, _maxListeners: undefined }
So the event of stream.on is not working for the acknowledge & also not syncing with the elasticsearch.

```javascript
var model = mongoose.model("MySearch", MySearch);
var stream = model.synchronize(function(err){
            console.log(err);
        })
        , count = 0;
    stream.on('data', function (err, doc) {
        count++;
    });
    stream.on('close', function () {
        console.log('indexed ' + count + ' documents from LeadSearch!');
    });
    stream.on('error', function (err) {
        console.log(err);
    });
```

**Comment by jan-swiecki** [comment]
Same problem. Model.synchronize doesn't do anything.

**Comment by jan-swiecki** [comment]
@kishankachchhi check if you are connected to Mongoose instance. I've had similar problem and mongoose didn't throw error when I was not connected to MongoDB.

**Comment by johannds** [comment]
Nope. This does not seem to work for me either. I've populated a database with a few documents, ran the exact code from the example. It shows "indexed 3 documents", but if I console.log the documents being indexed through stream.on("data") I see 'undefined' coming through. 

Any ideas?

**Comment by jan-swiecki** [comment]
@johannds Do they appear in Elasticsearch? I think I had the same problem - it is a bug, but they get indexed AFAIK.

**Comment by johannds** [comment]
Yup. There just seems to be a big delay in them showing up in ES.

**Comment by johannds** [comment]
Also found that if I don't create the index explicitly via CURL, it doesn't work.

**Comment by joshbedo** [comment]
I'm also experiencing the same problem. I have a fresh install of elasticsearch and i'm trying to synchronize my existing user model which shows it indexed a few documents but adding `console.log` on the data stream event i see undefined. Also when i go to `http://127.0.0.1:9200/users/_search?pretty=1` i see `index undefined exception`. Anybody solve this?

**Comment by py09mb** [comment]
Having the same issue, the doc returned from the data stream is undefined but they are being indexed in elastic search. If this is your problem you could try adding a post save method to your schema. In my example I have a field on the document which tracks if it has been indexed by ES. So I call synchronize with a query { indexed: { exists: false } } and then set the propery post save. 

    schema.methods.syncIndex = function (done) {
        var query = { _id: this._id };
        var update = { $set: { indexed: true } };
        this.model('Alert').update(query, update, done);
    };

    schema.post('save', function (doc, done) {
        return !this.indexed && this.syncIndex.call(this, done);
    });

**Comment by yonib05** [comment]
I am also having this issue. My data in ES is not being updated properly despite re-syncing.

**Comment by johannds** [comment]
I've dropped the library in favour of custom sync code in my post-save and
post-remove hooks. It seems to be working fine, even though it is more
onerous than using a library to take care of everything. My use case was
pretty simple, but I have code if anyone wants it.



Johann de Swardt

Founder

johann@aitako.com

+27 79 878 2057

**Comment by yonib05** [comment]
That would be wonderful if you could share your code. I'm under a tight deadline and writing up the code myself might set me back a bit.

**Comment by gmaniac** [comment]
Any update on this? I am getting `undefined` when trying to index pre-existing docs
