### ISSUE TITLE
mongoosastic 2.1.3 memory/cpu leak

### ISSUE THREAD

**Issue by maumercado** [mongoosastic/mongoosastic#88]
Im using node 0.10.35, mongoose 3.8.27 and mongoosastic 2.1.3

Whenever I do:

```
var stream = model.synchronize(query);

stream.on('data', function (err, doc){
    log.info(doc, "Sent to elastic search")
});
stream.on('close', function(){
    log.info('indexed documents!');
});
stream.on('error', function(err){
    log.error(err, "Error indexing selfie on elastic search");
});
```

The cpu usage goes up to 101% and the memory continues to grow until node fatal exception memory allocation is triggered.

Im trying to sync a collection with at least 60k records.

**Comment by jdelibas** [comment]
@maumercado give this PR a go. We werent measuring CPU usage on index but it definitely fixed memory issues we were having.

https://github.com/mongoosastic/mongoosastic/pull/85
