### ISSUE TITLE
Error with geo_code with Elasticsearch version 1.3.1

### ISSUE THREAD

**Issue by taterbase** [mongoosastic/mongoosastic#9]
https://github.com/jamescarr/mongoosastic/issues/114#issue-40421194

> Hi All,
> I'm getting this error when I index my models with the new version 1.3.1. Any ideas why?
> 
> ```
> { error: 'RemoteTransportException[...][index]]; nested: MapperParsingException[failed to parse]; nested: ElasticsearchParseException[field must be either \'lat\', \'lon\' or \'geohash\']; '
> ```
> 
> My mapping looks like this:
> 
> ```
>         location:
>           geo_point:
>             type       : String
>             es_type    : 'geo_point'
>             es_lat_lon : true
>           lat :
>             type: Number
>           lon :
>             type: Number
> ```

**Comment by guumaster** [comment]
Stale issue. closing.
