### ISSUE TITLE
esTruncate timing issue?

### ISSUE THREAD

**Issue by yuklai** [mongoosastic/mongoosastic#92]
Hi there,

I have the following code which I try to call esTruncate to clean up all User. 

```
User.remove({}, function(err) {
  assert(!err);
  User.esTruncate(function(err) {
    assert(!err);

    var userData = [{
      firstName: 'Peter',
      lastName: 'Griffin',
      email: 'peter@griffin.com'
    },
    {
      firstName: 'Lois',
      lastName: 'Griffin',
      email: 'lois@griffin.com'
    },
    {
      firstName: 'Brian',
      lastName: 'Griffin',
      email: 'brian@griffin.com'
    }];

    async.map(
      userData,
      function(userDatum, callback) {
        var user = new User(userDatum);
        user.save(function(err, user) {
          /* Document indexation on going */
          user.on('es-indexed', function(err, res) {
            callback(err, user);
          });
        });
      },
      callback
    );
  });
});
```

When I remove the esTruncate line, I can see that during the test I was able to search the user (though duplicated documents are created, which I was trying to avoid by esTruncate across multiple unit tests). But by adding esTruncate line, no user can be searched. It almost seems like the esTruncate call is deleting the index that I create later on. Is there a hidden timing issue that I'm not aware of when the truncate actually take effect? Thanks!

Yuk Lai

**Comment by guumaster** [comment]
There is a timing issue with ES operations. Each operation is "close-to-realtime" and it returns before it actually completed in all shards. If you look at the unit tests folder, you will see we use a delay between almost every ES operation and the assertion.
