### ISSUE TITLE
Mapping: when using mapping all the filed of objects are indexed automatically 

### ISSUE THREAD

**Issue by mhd999** [mongoosastic/mongoosastic#93]
i start using elasticsearch and mongoosastic just recently i understand the basics only.
what am trying to do is to index filed in the items object. 
First i used es_indexed:true in all the filed i want to index them 

	`title: {type: String, es_indexed:true},
	description: {type: String, es_indexed:true'},
	vendor: {type: String, es_indexed:true},`
Works fine on the _search i found the objects of items:
`{"_index":"items","_type":"item","_id":"55afe310eec377941cf70d44","_score":1.0,"_source":{"title":"dress to search","comments":[],"likes":[]}},{"_index":"items","_type":"item","_id":"55afe298eec377941cf70d43","_score":1.0,"_source":{"title":"dress to search","comments":[],"likes":[]}},{"_index":"items","_type":"item","_id":"55afe220eec377941cf70d42","_score":1.0,"_source":{"title":"dress to search","comments":[],"likes":[]}},`

I don't know why the comment and likes arrays are there! but it was fine.
Then i used mapping and my object field looked like this

`title: {type: String, es_boost:2.0},
description: {type: String, es_type:'string'},
vendor: {type: String, es_type:'string'},
vendorId: {type:String, es_type:'integer'},`

The problem here is under _search i found the object as it stored in the DB like this:
`{"_index":"items","_type":"item","_id":"55c4e127da55af70163636cd","_score":1.0,"_source":{"title":"dress to search","price":200,"description":"this is a dress to search","vendor":"Mohammad Al mouallem","vendorId":"552d84bb05da7ed000869585","totalComments":0,"totalLikes":0,"comments":[],"likes":[],"date":"2015-08-07T16:47:35.892Z"}}]}}`

all the fields are there now and i want to ask is this the right way of how elasticsearch working !

**Comment by jdelibas** [comment]
you could add `es_indexed:false` if you don't want fields to be indexed. 

AFAIK mongoosastic automatically indexes everything unless you tell it no to.

**Comment by guumaster** [comment]
As @jdelibas says, its a feature. If you want to remove something from the index, use `es_indexed:false`
