### ISSUE TITLE
Routing on save

### ISSUE THREAD

**Issue by yuklai** [mongoosastic/mongoosastic#95]
Hi there,
Is there any way I can define the routing a save uses?
I.e. https://www.elastic.co/guide/en/elasticsearch/guide/current/routing-value.html
Thanks!
Yuk Lai

**Comment by guumaster** [comment]
Can you provide us with some index/delete examples with routing in it?

**Comment by yuklai** [comment]
Hi @guumaster sorry not sure if I understand the sample you want, mind elaborating a little bit? 
The reason I asked about routing is to potentially devise a plan to allow separate shard per client company so their data don't intermix. Thanks!

**Comment by guumaster** [comment]
I can't find examples of routing in the ES docs. Do you have any example how to index a document with a specific routing?
