### ISSUE TITLE
Unable to remove reference from ES

### ISSUE THREAD

**Issue by MaximeHeckel** [mongoosastic/mongoosastic#96]
Hi

I encountered an issue today, I'm unable to remove the reference from ES when I'm removing the document from MongoDB, I went through the repos issue, and I'm doing a Model.remove() but it doesn't work.

```
File.remove({_id: req.query.id, author: req.user.username}, function(err, data){})
```

Is there a workaround ?

**Comment by MaximeHeckel** [comment]
I also tried this: 
File.find({_id: req.query.id, author: req.user.username}).remove(function(err, data){}) 

The deleted file is not removed from the index either

**Comment by yuklai** [comment]
did you try synchronize and wait for the 'close' event after remove?

**Comment by MaximeHeckel** [comment]
Thanks that worked perfectly.
I'm using mongoosastic for a long time but I never noticed this manual `synchronise` feature. This is really useful!

**Comment by guumaster** [comment]
It doesn't get deleted immediately, that0s a Elasticsearch feature. If you check the tests, you'll see that we have to add a delay until the element is actually removed from the index. And the exact time may vary. Even with `synchronize` this is the default ES behaviour.
